// This file has been autogenerated using CoD4X 1.8 server. //
// If it contains wrong data, please create issue here:     //
//    https://github.com/callofduty4x/CoD4x_Server/issues   //
#include code\utility;
init()
{
	players = getPlayers();
	sLoc = getLoc();
	sAng = getAng();
	
	waittillframeend;
	
	if( level.leiizko_dvars[ "end_music" ] )
		musicPlay( "end_game_1" );
	
	wait .75;
	
	for( i = 0; i < players.size; i++ )
	{
		player = players[i];
		
		player spawnSpec( sLoc, sAng );
		//player freezeControls( true );
		waittillframeend;
	}
	
	waittillframeend;

	getBestPlayers();
	thread credits();
	thread showPlayers();
	
	// 4+2+14
	
	wait 25;
	
	for( i=0; i<10; i++ )
	{
		if( isDefined( level.player[i] ) )
			level.player[i] destroy();
	}
	
	for( i=0; i<5; i++ )
	{
		if( isDefined( level.credit[i] ) )
			level.credit[i] destroy();
	}
}

setUp()
{
	thread code\events::addConnectEvent( ::onPlayerConnect );
	thread code\events::addDeathEvent( ::onPlayerKilled );
}

onPlayerConnect()
{
	if( !isDefined( self.pers["knifekills"] ) )
		self.pers["knifekills"] = 0;
		
	if( !isDefined( self.pers["nadekills"] ) )
		self.pers["nadekills"] = 0;
		
	if( !isDefined( self.pers["playersuicides"] ) )
		self.pers["playersuicides"] = 0;
		
	if( !isDefined( self.pers["playerHS"] ) )
		self.pers["playerHS"] = 0;
		
	if( !isDefined( self.pers["defuses"] ) )
		self.pers["defuses"] = 0;
		
	if( !isDefined( self.pers["plants"] ) )
		self.pers["plants"] = 0;
}

onPlayerKilled( eInflictor, attacker, iDamage, sMeansOfDeath, sWeapon, vDir, sHitLoc, psOffsetTime, deathAnimDuration )
{
	if( sMeansOfDeath == "MOD_MELEE" )
		self.pers["knifekills"]++;
	
	else if( sMeansOfDeath == "MOD_HEAD_SHOT" )
		self.pers["playerHS"]++;
		
	else if( sMeansOfDeath == "MOD_SUICIDE" || attacker == self )
		self.pers["playersuicides"]++;
		
	else if( sMeansOfDeath == "MOD_GRENADE" || sMeansOfDeath == "MOD_GRENADE_SPLASH" || sMeansOfDeath == "MOD_EXPLOSIVE" )
		self.pers["nadekills"]++;
}

showPlayers()
{
	// Kills //
	level.player[0] = newHudElem();
	level.player[0].alpha = 0;
	level.player[0].glowalpha = 0;
	level.player[0].horzAlign = "right";
	level.player[0].vertAlign = "middle";
	level.player[0].glowColor = ( randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ) );
	level.player[0].archived = false;
	level.player[0].alignX = "right";
	level.player[0].alignY = "middle";
	level.player[0].x = -20;
	level.player[0].y = -80;
	level.player[0].fontscale = 1.4;
	level.player[0].color = ( randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ) );
	
	if( level.playerskills > 0 )
		level.player[0] setText( "The Terminator: " + level.playerskills_ent.name + " with " + level.playerskills + " kills!" );
	else
		level.player[0] setText( "Only noobs here - 0 Kills made" );
	//  //
	
	// Score //
	level.player[1] = newHudElem();
	level.player[1].alpha = 0;
	level.player[1].glowalpha = 0;
	level.player[1].horzAlign = "right";
	level.player[1].vertAlign = "middle";
	level.player[1].glowColor = ( randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ) );
	level.player[1].archived = false;
	level.player[1].alignX = "right";
	level.player[1].alignY = "middle";
	level.player[1].x = -20;
	level.player[1].y = -60;
	level.player[1].fontscale = 1.4;
	level.player[1].color = ( randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ) );
	if( level.playerscore > 0 )
		level.player[1] setText( "" + level.playerscore_ent.name + " Played Super Mario Bros and got " + level.playerscore + " coins!" );
	else
		level.player[1] setText( "No coins picked up this game, zero kills made" );
	//  //
	
	// Deaths //
	level.player[2] = newHudElem();
	level.player[2].alpha = 0;
	level.player[2].glowalpha = 0;
	level.player[2].horzAlign = "right";
	level.player[2].vertAlign = "middle";
	level.player[2].glowColor = ( randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ) );
	level.player[2].archived = false;
	level.player[2].alignX = "right";
	level.player[2].alignY = "middle";
	level.player[2].x = -20;
	level.player[2].y = -40;
	level.player[2].fontscale = 1.4;
	level.player[2].color = ( randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ) );
	if( level.playerdeaths > 0 )
		level.player[2] setText( "" + level.playerdeaths_ent.name + " is Grims Reaper new best friend with " + level.playerdeaths + " deaths!" );
	else
		level.player[2] setText( "Grim Reaper was put out of job this game, noone died" );
	//  //
	
	// Assists //
	level.player[3] = newHudElem();
	level.player[3].alpha = 0;
	level.player[3].glowalpha = 0;
	level.player[3].horzAlign = "right";
	level.player[3].vertAlign = "middle";
	level.player[3].glowColor = ( randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ) );
	level.player[3].archived = false;
	level.player[3].alignX = "right";
	level.player[3].alignY = "middle";
	level.player[3].x = -20;
	level.player[3].y = -20;
	level.player[3].fontscale = 1.4;
	level.player[3].color = ( randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ) );
	if( level.assists > 0 )
		level.player[3] setText( "Marios new BF is " + level.assists_ent.name + " with his " + level.assists + " assists!" );
	else
		level.player[3] setText( "Super Mario was all alone this game, no assists made" );
	//  //
	
	// Suicides //
	level.player[4] = newHudElem();
	level.player[4].alpha = 0;
	level.player[4].glowalpha = 0;
	level.player[4].horzAlign = "right";
	level.player[4].vertAlign = "middle";
	level.player[4].glowColor = ( randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ) );
	level.player[4].archived = false;
	level.player[4].alignX = "right";
	level.player[4].alignY = "middle";
	level.player[4].x = -20;
	level.player[4].y = 0;
	level.player[4].fontscale = 1.4;
	level.player[4].color = ( randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ) );
	if( level.playersuicides > 0 )
		level.player[4] setText( "This games' unlucky bastard is " + level.playersuicides_ent.name + " with his " + level.playersuicides + " suicides!" );
	else
		level.player[4] setText( "One could say everyone was lucky this game, no suicides made" );
	//  //
	
	// HeadShots //
	level.player[5] = newHudElem();
	level.player[5].alpha = 0;
	level.player[5].glowalpha = 0;
	level.player[5].horzAlign = "right";
	level.player[5].vertAlign = "middle";
	level.player[5].glowColor = ( randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ) );
	level.player[5].archived = false;
	level.player[5].alignX = "right";
	level.player[5].alignY = "middle";
	level.player[5].x = -20;
	level.player[5].y = 20;
	level.player[5].fontscale = 1.4;
	level.player[5].color = ( randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ) );
	if( level.playerHS > 0 )
		level.player[5] setText( "Ultimate headhunter " + level.playerHS_ent.name + " with " + level.playerHS + " headshots!" );
	else
		level.player[5] setText( "No real man was found this game, no headshots made" );
	//  //

	// knife kills //
	level.player[6] = newHudElem();
	level.player[6].alpha = 0;
	level.player[6].glowalpha = 0;
	level.player[6].horzAlign = "right";
	level.player[6].vertAlign = "middle";
	level.player[6].glowColor = ( randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ) );
	level.player[6].archived = false;
	level.player[6].alignX = "right";
	level.player[6].alignY = "middle";
	level.player[6].x = -20;
	level.player[6].y = 40;
	level.player[6].fontscale = 1.4;
	level.player[6].color = ( randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ) );
	if( level.knifekills > 0 )
		level.player[6] setText( "Watch out! We have a Ninja " + level.knifekills_ent.name + " here with " + level.knifekills + " butchered enemies!" );
	else
		level.player[6] setText( "Phew, no hidden ninja this game, no butchered people" );
	//  //
	
	// nade kills //
	level.player[7] = newHudElem();
	level.player[7].alpha = 0;
	level.player[7].glowalpha = 0;
	level.player[7].horzAlign = "right";
	level.player[7].vertAlign = "middle";
	level.player[7].glowColor = ( randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ) );
	level.player[7].archived = false;
	level.player[7].alignX = "right";
	level.player[7].alignY = "middle";
	level.player[7].x = -20;
	level.player[7].y = 60;
	level.player[7].fontscale = 1.4;
	level.player[7].color = ( randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ) );
	if( level.nadekills > 0 )
		level.player[7] setText( "" + level.nadekills_ent.name + " likes blowing stuff up with " + level.nadekills + " explosive kills!" );
	else
		level.player[7] setText( "Does no one know how to cause some explosive mayhem? no explosive kills" );
	//  //
	
	// plants //
	level.player[8] = newHudElem();
	level.player[8].alpha = 0;
	level.player[8].glowalpha = 0;
	level.player[8].horzAlign = "right";
	level.player[8].vertAlign = "middle";
	level.player[8].glowColor = ( randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ) );
	level.player[8].archived = false;
	level.player[8].alignX = "right";
	level.player[8].alignY = "middle";
	level.player[8].x = -20;
	level.player[8].y = 80;
	level.player[8].fontscale = 1.4;
	level.player[8].color = ( randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ) );
	if( level.plants > 0 )
		level.player[8] setText( "Demolition expert " + level.plants_ent.name + " planted " + level.plants + " bombs!" );
	else
		level.player[8] setText( "Everyone decided to play TDM so no bombs were planted" );
	//  //
	
	// defuses //
	level.player[9] = newHudElem();
	level.player[9].alpha = 0;
	level.player[9].glowalpha = 0;
	level.player[9].horzAlign = "right";
	level.player[9].vertAlign = "middle";
	level.player[9].glowColor = ( randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ) );
	level.player[9].archived = false;
	level.player[9].alignX = "right";
	level.player[9].alignY = "middle";
	level.player[9].x = -20;
	level.player[9].y = 100;
	level.player[9].fontscale = 1.4;
	level.player[9].color = ( randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ) );
	if( level.defuses > 0 )
		level.player[9] setText( "Bomb squad leader " + level.defuses_ent.name + " defused " + level.defuses + " bombs!" );
	else
		level.player[9] setText( "Better call Saul to help you defuse explosives next time" );
	//  //
	
	for( i=0; i<10; i++ )
	{
		level.player[i] fadeOverTime( 2 );
		level.player[i].alpha = 1;
		
		wait .8;
	}
}

getBestPlayers()
{
	level.playerscore = 0;
	level.playerHS = 0;
	level.knifekills = 0;
	level.playerdeaths = 0;
	level.playerskills = 0;
	level.plants = 0;
	level.defuses = 0;
	level.playersuicides = 0;
	level.nadekills = 0;
	level.assists = 0;

	players = getEntarray( "player", "classname" );
	for( i=0; i<players.size; i++ )
	{
		player = players[i];
		
		if( !isDefined( player ) || !isPlayer( player ) )
			continue;
		
		if( player.pers[ "plants" ] > level.plants )
		{
			level.plants = player.pers[ "plants" ];
			level.plants_ent = player;
		}
		
		if( player.pers[ "defuses" ] > level.defuses )
		{
			level.defuses = player.pers[ "defuses" ];
			level.defuses_ent = player;
		}
		
		if( player.pers[ "kills" ] > level.playerskills )
		{
			level.playerskills = player.pers[ "kills" ];
			level.playerskills_ent = player;
		}
		
		if( player.pers[ "deaths" ] > level.playerdeaths )
		{
			level.playerdeaths = player.pers[ "deaths" ];
			level.playerdeaths_ent = player;
		}
		
		if( player.pers[ "assists" ] > level.assists )
		{
			level.assists = player.pers[ "assists" ];
			level.assists_ent = player;
		}
		
		if( player.pers[ "score" ] > level.playerscore )
		{
			level.playerscore = player.pers[ "score" ];
			level.playerscore_ent = player;
		}
		
		if( player.pers[ "knifekills" ] > level.knifekills )
		{
			level.knifekills = player.pers[ "knifekills" ];
			level.knifekills_ent = player;
		}
		
		if( player.pers[ "nadekills" ] > level.nadekills )
		{
			level.nadekills = player.pers[ "nadekills" ];
			level.nadekills_ent = player;
		}
		
		if( player.pers[ "playersuicides" ] > level.playersuicides )
		{
			level.playersuicides = player.pers[ "playersuicides" ];
			level.playersuicides_ent = player;
		}
		
		if( player.pers[ "playerHS" ] > level.playerHS )
		{
			level.playerHS = player.pers[ "playerHS" ];
			level.playerHS_ent = player;
		}
		
		waittillframeend;
	}
}

credits() // 640x480 
{
	level.credit[0] = newHudElem();
	level.credit[0] setText( "Credits:" );
	level.credit[0].alpha = 0;
	level.credit[0].glowalpha = 0;
	level.credit[0].horzAlign = "left";
	level.credit[0].vertAlign = "bottom";
	level.credit[0].glowColor = ( randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ) );
	level.credit[0].archived = false;
	level.credit[0].alignX = "left";
	level.credit[0].alignY = "bottom";
	level.credit[0].x = 50;
	level.credit[0].y = -200;
	level.credit[0].fontscale = 2;
	level.credit[0].color = ( randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ) );
	
	level.credit[1] = newHudElem();
	level.credit[1] setText( "{MiCkEy}.ViRuS" );
	level.credit[1].alpha = 0;
	level.credit[1].glowalpha = 0;
	level.credit[1].horzAlign = "left";
	level.credit[1].vertAlign = "bottom";
	level.credit[1].glowColor = ( randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ) );
	level.credit[1].archived = false;
	level.credit[1].alignX = "left";
	level.credit[1].alignY = "bottom";
	level.credit[1].x = 50;
	level.credit[1].y = -180;
	level.credit[1].fontscale = 1.5;
	level.credit[1].color = ( randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ) );
	
	level.credit[2] = newHudElem();
	level.credit[2] setText( "www.ViRuSGaminG.xyz" );
	level.credit[2].alpha = 0;
	level.credit[2].glowalpha = 0;
	level.credit[2].horzAlign = "left";
	level.credit[2].vertAlign = "bottom";
	level.credit[2].glowColor = ( randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ) );
	level.credit[2].archived = false;
	level.credit[2].alignX = "left";
	level.credit[2].alignY = "bottom";
	level.credit[2].x = 50;
	level.credit[2].y = -160;
	level.credit[2].fontscale = 1.5;
	level.credit[2].color = ( randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ) );
	
	level.credit[3] = newHudElem();
	level.credit[3] setText( "Thank's To ViRuS GaminG Team" );
	level.credit[3].alpha = 0;
	level.credit[3].glowalpha = 0;
	level.credit[3].horzAlign = "left";
	level.credit[3].vertAlign = "bottom";
	level.credit[3].glowColor = ( randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ) );
	level.credit[3].archived = false;
	level.credit[3].alignX = "left";
	level.credit[3].alignY = "bottom";
	level.credit[3].x = 50;
	level.credit[3].y = -140;
	level.credit[3].fontscale = 1.5;
	level.credit[3].color = ( randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ) );
	
	if( level.leiizko_dvars[ "scr_credit_text" ] != "" )
	{
		level.credit[4] = newHudElem();
		level.credit[4] setText( level.leiizko_dvars[ "scr_credit_text" ] );
		level.credit[4].alpha = 0;
		level.credit[4].glowalpha = 0;
		level.credit[4].horzAlign = "center";
		level.credit[4].vertAlign = "top";
		level.credit[4].glowColor = ( randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ) );
		level.credit[4].archived = false;
		level.credit[4].alignX = "center";
		level.credit[4].alignY = "top";
		level.credit[4].x = 0;
		level.credit[4].y = -20;
		level.credit[4].fontscale = 2.4;
		level.credit[4].color = ( randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ), randomFloatRange( 0, 1 ) );
	}
	
	for( i=0; i<5; i++ )
	{
		level.credit[i] fadeOverTime( 2 );
		level.credit[i].alpha = 1;
		
		if( i == 4 )
		{
			level.credit[i] moveOverTime( 4 );
			level.credit[i].y = 80;
		}
		
		wait 1;
	}
	
	wait 5;
	
	for( i=0; i<4; i++ )
	{
		level.credit[i] fadeOverTime( 3 );
		level.credit[i].alpha = 0;
		
		wait 1.5;
	}
}