/*===================================================================||
||/|―――――――\///|――|/////|――|//|―――――――――|//|―――――――――|//\――\/////――//||
||/|  |//\  \//|  |/////|  |//|  |/////////|  |//////////\  \///  ///||
||/|  |///\  \/|  |/////|  |//|  |/////////|  |///////////\  \/  ////||
||/|  |///|  |/|  |/////|  |//|   _____|///|   _____|//////\    /////||
||/|  |////  //|  \/////|  |//|  |/////////|  |/////////////|  |/////||
||/|  |///  ////\  \////  ////|  |/////////|  |/////////////|  |/////||
||/|_______//////\_______/////|__|/////////|__|/////////////|__|/////||
||===================================================================||
||     DO NOT USE, SHARE OR MODIFY THIS FILE WITHOUT PERMISSION      ||
||===================================================================*/

#include duffman\_languages;

LoadLanguages() {
	//-------------------------ENGLISH-------------------------
	Lang("EN", "VIP_DM",					"DeathMachine ON/OFF");
	Lang("EN", "VIP_FREEZE",				"FreezeAll ON/OFF");
	Lang("EN", "VIP_INVIS",					"Invisible ON/OFF");
	Lang("EN", "VIP_PICKUP",				"Pickup ON/OFF");
	Lang("EN", "VIP_NUKEBULL",				"NukeBullets");
	Lang("EN", "VIP_DOGOD",					"GodMode On");
	Lang("EN", "VIP_NOVA",					"GAS Nade");
	Lang("EN", "VIP_ROCKNUKE",				"Rocket Nuke");
	Lang("EN", "VIP_JETPACK",				"Jetpack");
	Lang("EN", "VIP_TELEGUN",				"Telegun");
	Lang("EN", "VIP_AMMO",					"Ammo");
	
	Lang("EN", "YOUR_BOUNCED",				"^5You were ^7bounced ^5by the Admin");
	Lang("EN", "BOUNCED_NOTIFY",			"$$CLANTAG$$[admin]: ^5Bounced ^7$$NAME$$.");
	Lang("EN", "APPEAR_AFK",				"^5You appear to be ^7AFK!");
	Lang("EN", "IS_AFK",					"$$NAME$$ ^5appears to be ^7AFK!");
	Lang("EN", "MOVE_OR_KILL",				"^5Move or you will be ^7killed!");
	Lang("EN", "ARTILLERY_NOT_AVAILABLE",	"Artillery not available");
	Lang("EN", "PREDATOR_NOT_AVAILABLE",	"Predator not available");
	Lang("EN", "STRAFE_NOT_AVAILABLE",		"Strafe Run not available");	
	Lang("EN", "PREDATOR_STAND",			"You have to stand while using a Predator");
	Lang("EN", "PREDATOR_INCOMING",			"Predator incoming");
	Lang("EN", "FRIENDLY_PREDATOR",			"Friendly Predator incoming");
	Lang("EN", "ENEMY_PREDATOR",			"Enemy Predator incoming");
	Lang("EN", "ARTILLERY_INCOMING",		"Artillery standing by");
	Lang("EN", "FRIENDLY_ARTILLERY",		"Friendly Artillery standing by");
	Lang("EN", "ENEMY_ARTILLERY",			"Enemy Artillery standing by");
	Lang("EN", "STRAFE_INCOMING",			"Strafe Run incoming");
	Lang("EN", "FRIENDLY_STRAFE",			"Friendly Strafe Run incoming");
	Lang("EN", "ENEMY_STRAFE",				"Enemy Strafe Run incoming");
	Lang("EN", "PACKAGE_INCOMING",			"Care Package incoming");
	Lang("EN", "FRIENDLY_PACKAGE",			"Friendly Care Package incoming");
	Lang("EN", "ENEMY_PACKAGE",				"Enemy Care Package incoming");
	Lang("EN", "PACKAGE_POSITION",			"You cant call a Care Package at this position");
	Lang("EN", "START_MAPVOTE",				"Press Fire to Vote");
	Lang("EN", "MAX_PRESTIGE",				"You already reached the max prestige level!");
	Lang("EN", "NOT_REACHED_LVL",			"You havent reached lv 55 yet");
	Lang("EN", "PRESTIGE_KILLS_LEFT",		"There are still $$KILLS$$ kills left!");
	Lang("EN", "WELCOME",					"Welcome");
	Lang("EN", "FRAG_WAIT",					"You have to wait $$TIME$$ seconds");
	Lang("EN", "predator_mp",				"Press [{+actionslot 4}] for PREDATOR");
	Lang("EN", "artillery_mp",				"Press [{+actionslot 4}] for ARTILLERY");
	Lang("EN", "carepackage_mp",			"Press [{+actionslot 4}] for CARE PACKAGE");
	Lang("EN", "strafe_mp",					"Press [{+actionslot 4}] for Strafe Run");	
	Lang("EN", "PICKUP",					"Press ^3[[{+usereload}]] ^7to pickup Carepackage");	
	Lang("EN", "NINJA",						"You got ability Ninja!");	
	Lang("EN", "RUSHER",					"You got ability Rusher!");	
	Lang("EN", "JUGGERNAUT",				"You got ability Juggernaut!");	
	Lang("EN", "NUKE_BULLETS",				"You got Nuke bullets!");	
	Lang("EN", "ACCURACY",				 	&"^2Accuracy:^7 &&1");
	Lang("EN", "HELP_1",					"This Server offers many new features to improve your\ngaming experience, therefore theres a Menu where you\ncan enter prestige and change some graphic settings.\nIt can be opened by pressing Nightvision-button twice\nor by typing '!menu' into the chat."); // THIS TEXT MUST BE SHORTER THEN 256 chars
	Lang("EN", "HELP_2",					"The emblemtext can be changed by typing:\n!emblem <YOUR TEXT>");
	Lang("EN", "HELP_CLOSE",				"Press ^3[[{+melee}]] ^7to close this menu!");
	Lang("EN", "HELP_TIME_LEFT",			&"&&1 seconds left untill you can close!");
	Lang("EN", "MENU_NAVI",					"^7Select: ^3[Right or Left Mouse]^7\nUse: ^3[[{+activate}]]^7\nLeave: ^3[[{+melee}]]");
	Lang("EN", "PRESTIGE_UNLOCK",			"You have to reach Prestige level $$LEVEL$$ to unlock $$FEATURE$$");
	Lang("EN", "NO_PERMISSION",				"You have no permission to use this!\nFailed on Permission: $$PERMISSION$$");
	Lang("EN", "REFLECT_ON",				"Damage Reflection ^5activated due to camp!");
	Lang("EN", "SPAWN_PROTECTION",			&"Spawnprotection...^3&&1");
	Lang("EN", "REAPER",					"Press [{+actionslot 4}] for Reaper");
	Lang("EN", "REAPER_NOT_AVAILABLE",		"Reaper not available");
	Lang("EN", "REAPER_INCOMING",			"Reaper incoming");
	Lang("EN", "FRIENDLY_REAPER",			"Friendly Reaper incoming");
	Lang("EN", "ENEMY_REAPER",				"Enemy Reaper incoming");
	Lang("EN", "nuke_mp",					"Press [{+actionslot 4}] for NUKE");
	Lang("EN", "NUKE_NOT_AVAILABLE",		"Nuke not available");	
	Lang("EN", "NUKE_INCOMING",				"Nuke incoming");
	Lang("EN", "FRIENDLY_NUKE",				"Friendly Nuke incoming");
	Lang("EN", "ENEMY_NUKE",				"Enemy Nuke incoming");		
	Lang("EN", "TRAINING_AREA",				"Press ^3[USE] ^7to enter training area");
	Lang("EN", "GOT_KILLED",				&"Killed by &&1.");	
	Lang("EN", "KILLED_PLAYER",				&"You killed &&1.");
	Lang("EN", "GOT_HONORED",				"You've got honored by $$NAME$$");
	Lang("EN", "HONOR_PLAYER",				&"Press ^3[FLASH] ^7to honor ^7&&1 for this Kill.");
	Lang("EN", "CURRENT_HONOR",				&"Collected &&1 honors.");
	Lang("EN", "MENU_PRESTIGE",				"Enter Prestige");
	Lang("EN", "MENU_LASER",				"Toggle reflex Laser (Prestige 3)");
	Lang("EN", "MENU_THERMAL",				"Toggle Thermal (Prestige 2)");
	Lang("EN", "MENU_EMBLEM",				"Change Emblem (Prestige 1)");
	Lang("EN", "MENU_EMBLEM_DEFAULT",		"Default Design");
	Lang("EN", "MENU_EMBLEM_BLUE",			"Blue Design");
	Lang("EN", "MENU_EMBLEM_RED",			"Red Design");
	Lang("EN", "MENU_EMBLEM_GREEN",			"Green Design");
	Lang("EN", "MENU_EMBLEM_YELLOW",		"Yellow Design");
	Lang("EN", "MENU_EMBLEM_ADMIN",			"RS-Member Design");
	Lang("EN", "MENU_EMBLEM_OWN",			"Submit own theme");
	Lang("EN", "MENU_FILM",					"Select Filmtweaks");
	Lang("EN", "MENU_TWEAK",				"Tweakables");
	Lang("EN", "MENU_BRIGHT",				"Toggle Fullbright");
	Lang("EN", "MENU_FOG",					"Toggle Fog");
	Lang("EN", "MENU_LASER2",				"Toggle Laser");
	Lang("EN", "MENU_RULES",				"Switch Gamerules");
	Lang("EN", "MENU_RESET",				"Reset all");
	Lang("EN", "MENU_TWEAKS",				"Toggle Filmtweaks");
	Lang("EN", "MENU_DEV",					"Admin section");
	Lang("EN", "MENU_VIP",					"Vip section");
	Lang("EN", "MENU_EDITOR",				"Create a Class");
	Lang("EN", "RESPAWN_IN",				&"Respawning in: &&1");
	Lang("EN", "EARNED_XP",					&"^5Earned XP: ^7&&1");
	Lang("EN", "ONLY_WELCOME",				"^5We are currently playing only ^7$$MODE$$");
	Lang("EN", "ONLY_CHANGED",				"^5Only mode got changed to ^7$$MODE$$");	
	Lang("EN", "ONLY_RESETED",				"^5Only mode got ^5reset");
	Lang("EN", "TRANSLATED_BY",				"English translation by DuffMan & Borrow");
	
	Lang("EN", "REAPER",					"Press [{+actionslot 4}] for Reaper");
	Lang("EN", "REAPER_NOT_AVAILABLE",		"Reaper not available");
	Lang("EN", "REAPER_INCOMING",				"Reaper incoming");
	Lang("EN", "FRIENDLY_REAPER",				"Friendly Reaper incoming");
	Lang("EN", "ENEMY_REAPER",				"Enemy Reaper incoming");

	Lang("EN", "orbital_mp",				"Press [{+actionslot 4}] for Orbital Satellite");	
	Lang("EN", "ORBITAL_INCOMING",			"Orbital Satellite called in for 20 seconds");
	Lang("EN", "FRIENDLY_ORBITAL",			"Orbital Satellite called in for 20 seconds");
	Lang("EN", "ENEMY_ORBITAL",				"Enemy Orbital Satellite called in for 20 seconds");	
	Lang("EN", "ORBITAL_EXPIRED",			"Orbital Satellite offline");

	Lang("EN", "TEAM_BALANCE_FALSE",		"Theres no need to balance the teams");	
	Lang("EN", "TEAM_BALANCE_ONCE",			"You can only call teambalance once a map");	
	Lang("EN", "MENU_CHANGELOG",			"View Changelog");			
	//--------------------------GERMAN-------------------------
	Lang("DE", "VIP_DM",					"DeathMachine ON/OFF");
	Lang("DE", "VIP_FREEZE",				"FreezeAll ON/OFF");
	Lang("DE", "VIP_INVIS",					"Invisible ON/OFF");
	Lang("DE", "VIP_PICKUP",				"Pickup ON/OFF");
	Lang("DE", "VIP_NUKEBULL",				"NukeBullets");
	Lang("DE", "VIP_DOGOD",					"GodMode On");
	Lang("DE", "VIP_NOVA",					"GAS Nade");
	Lang("DE", "VIP_ROCKNUKE",				"Rocket Nuke");
	Lang("DE", "VIP_JETPACK",				"Jetpack");
	Lang("DE", "VIP_TELEGUN",				"Telegun");
	Lang("DE", "VIP_AMMO",					"Ammo");
	
	Lang("DE", "REAPER",					"Drόcken Sie [{+actionslot 4}] fόr Schnitter");
	Lang("DE", "REAPER_NOT_AVAILABLE",		"Schnitter nicht verfόgbar");
	Lang("DE", "REAPER_INCOMING",				"Schnitter eingehend");
	Lang("DE", "FRIENDLY_REAPER",				"freundlich Schnitter eingehend");
	Lang("DE", "ENEMY_REAPER",				"Feind Schnitter eingehend");
	Lang("DE", "YOUR_BOUNCED",				"^5Du wurdest von einem ^7Admin gebounct.");
	Lang("DE", "BOUNCED_NOTIFY",			"$$CLANTAG$$[Admin]: ^5Spieler ^7$$NAME$$ ^5wurde gebounct.");
	Lang("DE", "APPEAR_AFK",				"^5Du scheinst ^7AFK ^5zu sein!");
	Lang("DE", "IS_AFK",					"$$NAME$$ ^5scheint ^7AFK ^5zu sein!");
	Lang("DE", "MOVE_OR_KILL",				"^5Bewege dich oder du wirst ^7getφtet!");
	Lang("DE", "ARTILLERY_NOT_AVAILABLE",	"Artillery nicht verfόgbar");
	Lang("DE", "PREDATOR_NOT_AVAILABLE",	"Predator nicht verfόgbar");
	Lang("DE", "STRAFE_NOT_AVAILABLE",		"Strafe Run nicht verfόgbar");	
	Lang("DE", "PREDATOR_STAND",			"Du musst stehen um die Predator zu nutzen");
	Lang("DE", "PREDATOR_INCOMING",			"Predator bereit");
	Lang("DE", "FRIENDLY_PREDATOR",			"Verbόndete Predator bereit");
	Lang("DE", "ENEMY_PREDATOR",			"Feindliche Predator bereit");
	Lang("DE", "ARTILLERY_INCOMING",		"Artillery steht bereit");
	Lang("DE", "FRIENDLY_ARTILLERY",		"Verbόndete Artillery steht bereit");
	Lang("DE", "ENEMY_ARTILLERY",			"Feindliche Artillery steht bereit");
	Lang("DE", "STRAFE_INCOMING",			"Strafe Run bereit");
	Lang("DE", "FRIENDLY_STRAFE",			"Verbόndeter Strafe Run bereit");
	Lang("DE", "ENEMY_STRAFE",				"Feindlicher Strafe Run bereit");
	Lang("DE", "PACKAGE_INCOMING",			"Vorrδte kommen herbei");
	Lang("DE", "FRIENDLY_PACKAGE",			"Verbόndete Vorrδte kommen herbei");
	Lang("DE", "ENEMY_PACKAGE",				"Feindliche Vorrδte kommen herbei");
	Lang("DE", "PACKAGE_POSITION",			"Du kannst keine Vorrδte zu dieser Position rufen");
	Lang("DE", "START_MAPVOTE",				"Drόcke [Schieίen] um zu voten");
	Lang("DE", "MAX_PRESTIGE",				"Du hast bereits das hφchste Prestige Level erreicht");
	Lang("DE", "NOT_REACHED_LVL",			"Du hast Level 55 noch nicht erreicht");
	Lang("DE", "PRESTIGE_KILLS_LEFT",		"Du benφtigst noch $$KILLS$$ Treffer!");
	Lang("DE", "WELCOME",					"Servus");
	Lang("DE", "FRAG_WAIT",					"Du musst $$TIME$$ Sekunden warten");	
	Lang("DE", "predator_mp",				"Drόcke [{+actionslot 4}] fόr PREDATOR");
	Lang("DE", "artillery_mp",				"Drόcke [{+actionslot 4}] fόr ARTILLERY");
	Lang("DE", "carepackage_mp",			"Drόcke [{+actionslot 4}] fόr CARE PACKAGE");
	Lang("DE", "strafe_mp",					"Drόcke [{+actionslot 4}] fόr Strafe Run");	
	Lang("DE", "PICKUP",					"Drόcke ^3[[{+usereload}]] ^7um das Carepackage aufzunehmen");	
	Lang("DE", "NINJA",						"Du hast die Fδhigkeit 'Ninja' bekommen");	
	Lang("DE", "RUSHER",					"Du hast die Fδhigkeit 'Rusher' bekommen");	
	Lang("DE", "JUGGERNAUT",				"Du hast die Fδhigkeit 'Juggernaut' bekommen");	
	Lang("DE", "NUKE_BULLETS",				"Du hast 'Nuke Bullets' bekommen");		
	Lang("DE", "ACCURACY",					&"^5Trefferrate:^7 &&1");
	Lang("DE", "HELP_1",					"Dieser Server bietet viele neue Funktionen um den\nSpielspaί zu verbessern. Daher gibt es ein extra Menό,\nin dem du z.B. in den Prestige Modus gelangst.\nEs kann geφffnet werden indem du 2 mal den Nachtsicht Knopf drόckst\noder '!menu' in den Chat schreibst"); // THIS TEXT MUST BE SHORTER THEN 256 chars
	Lang("DE", "HELP_2",					"Schreibe folgendes in den Chat um deinen Emblemtext zu δndern:\n!emblem <DEIN TEXT>");
	Lang("DE", "HELP_CLOSE",				"Drόcke ^3[[{+melee}]] ^7um das Menό zu schlieίen!");
	Lang("DE", "HELP_TIME_LEFT",			&"&&1 Sekunden verbleibend.");
	Lang("DE", "MENU_NAVI",					"^7Auswδhlen: ^3[Rechte oder Linke Maus]^7\nBestδtigen: ^3[[{+activate}]]^7\nVerlassen: ^3[[{+melee}]]");
	Lang("DE", "PRESTIGE_UNLOCK",			"Du musst das Prestige Level $$LEVEL$$ erreichen um $$FEATURE$$ freizuschalten");
	Lang("DE", "NO_PERMISSION",				"Du hast keine Berechtigung dies zu benutzen!\nBenφtigte Rechte: $$PERMISSION$$");
	Lang("DE", "REFLECT_ON",				"Schaden Reflektion ^5wegen Campen aktiviert!");
	Lang("DE", "SPAWN_PROTECTION",			&"Spawnschutz...^3&&1");
	Lang("DE", "nuke_mp",					"Drόcke [{+actionslot 4}] fόr Atombombe");
	Lang("DE", "NUKE_NOT_AVAILABLE",		"Atombombe nicht verfόgbar");	
	Lang("DE", "NUKE_INCOMING",				"Atombombe bereit!");
	Lang("DE", "FRIENDLY_NUKE",				"Verbόndete Atombombe bereit!");
	Lang("DE", "ENEMY_NUKE",				"Feindlich Atombombe bereit!");	
	Lang("DE", "GOT_KILLED",				&"Getφtet von &&1.");	
	Lang("DE", "KILLED_PLAYER",				&"Sie schalten &&1 aus.");
	Lang("DE", "GOT_HONORED",				"Du wurdest von $$NAME$$ geehrt!");
	Lang("DE", "HONOR_PLAYER",				&"Drόcke ^3[FLASH] ^7um &&1 fόr diesen Kill zu Ehren.");
	Lang("DE", "CURRENT_HONOR",				&"&&1 erhaltene Ehrungen.");
	Lang("DE", "TRAINING_AREA",				"Drόcke ^3[BENUTZEN] ^7um ins Trainingslager zu gelangen.");
	Lang("DE", "MENU_PRESTIGE",				"Prestige betreten");
	Lang("DE", "MENU_LASER",				"Laser ein/aus (Prestige 3)");
	Lang("EN", "MENU_THERMAL",				"Toggle Thermal (Prestige 2)");
	Lang("DE", "MENU_EMBLEM",				"Emblem δndern (Prestige 1)");
	Lang("DE", "MENU_EMBLEM_BLUE",			"Blaues Design");
	Lang("DE", "MENU_EMBLEM_RED",			"Rotes Design");
	Lang("DE", "MENU_EMBLEM_GREEN",			"Grόnes Design");
	Lang("DE", "MENU_EMBLEM_YELLOW",		"gelb Design");
	Lang("DE", "MENU_EMBLEM_ADMIN",			"RS-Mitglied Design");
	Lang("DE", "MENU_EMBLEM_DEFAULT",		"Standart Design");
	Lang("DE", "MENU_EMBLEM_3RS",			"^1RS^7' Stile");
	Lang("DE", "MENU_EMBLEM_OWN",			"Eigenes Design vorschlagen");
	Lang("DE", "MENU_FILM",					"Filmtweaks auswδhlen");
	Lang("DE", "MENU_TWEAK",				"Spieleinstellungen");
	Lang("DE", "MENU_BRIGHT",				"Fullbright umschalten");
	Lang("DE", "MENU_FOG",					"Rauch umschalten");
	Lang("DE", "MENU_LASER2",				"Laser umschalten");
	Lang("DE", "MENU_RULES",				"Spielregeln δndern");
	Lang("DE", "MENU_RESET",				"Alles zurόcksetzen");
	Lang("DE", "MENU_TWEAKS",				"Filmtweaks ein/aus");
	Lang("DE", "MENU_DEV",					"Adminbereich");
	Lang("DE", "MENU_VIP",					"Vip section");
	Lang("DE", "MENU_EDITOR",				"Klasseneditor");
	Lang("DE", "RESPAWN_IN",				&"Wiedereinstieg in: &&1");
	Lang("DE", "EARNED_XP",					&"^5Erhaltene EP: ^7&&1");
	Lang("DE", "ONLY_WELCOME",				"^5Wir spielen momentan nur ^7$$MODE$$!");
	Lang("DE", "ONLY_CHANGED",				"^5Spielmodus wurde in ^7$$MODE$$ ^5geδndert!");	
	Lang("DE", "ONLY_RESETED",				"^5Spielmodus wurde zurόck gesetzt!");
	Lang("DE", "TRANSLATED_BY",				"Deutsche άbersetzungen von DuffMan & Borrow");

	Lang("DE", "orbital_mp",				"Drόcke [{+actionslot 4}] fόr Orbital Satellit");	
	Lang("DE", "ORBITAL_INCOMING",			"Orbital Satellit fόr 20 Sekunden verfόgbar");
	Lang("DE", "FRIENDLY_ORBITAL",			"Orbital Satellit fόr 20 Sekunden verfόgbar");
	Lang("DE", "ENEMY_ORBITAL",				"Feind erhδlt Orbital Satellit fόr 20 Sekunden");

	Lang("DE", "TEAM_BALANCE_FALSE",		"Die Teams mόssen nicht ausgeglichen werden");	
	Lang("DE", "TEAM_BALANCE_ONCE",			"Du kannst den Teamausgleich nur einmal pro Karte ausfόhren");	

	Lang("DE", "MENU_CHANGELOG",			"Δnderungsprotokoll");	
	//-------------------------HUNGARY-------------------------
	Lang("HU", "VIP_DM",					"DeathMachine ON/OFF");
	Lang("HU", "VIP_FREEZE",				"FreezeAll ON/OFF");
	Lang("HU", "VIP_INVIS",					"Invisible ON/OFF");
	Lang("HU", "VIP_PICKUP",				"Pickup ON/OFF");
	Lang("HU", "VIP_NUKEBULL",				"NukeBullets");
	Lang("HU", "VIP_DOGOD",					"GodMode On");
	Lang("HU", "VIP_NOVA",					"GAS Nade");
	Lang("HU", "VIP_ROCKNUKE",				"Rocket Nuke");
	Lang("HU", "VIP_JETPACK",				"Jetpack");
	Lang("HU", "VIP_TELEGUN",				"Telegun");
	Lang("HU", "VIP_AMMO",					"Ammo");
	
	Lang("HU", "REAPER",					"sajtσ [{+actionslot 4}] mert Schnitter");
	Lang("HU", "REAPER_NOT_AVAILABLE",		"Schnitter nem rendelkezιsre αllσ");
	Lang("HU", "REAPER_INCOMING",				"Schnitter bejφvo");
	Lang("HU", "FRIENDLY_REAPER",				"barαtsαgos Schnitter bejφvo");
	Lang("HU", "ENEMY_REAPER",				"ellensιg Schnitter bejφvo");
	Lang("HU", "YOUR_BOUNCED",				"^7Rφptetve^5 lettιl az Admin αltal.");
	Lang("HU", "BOUNCED_NOTIFY",			"$$CLANTAG$$[admin]: ^5Rφptette: ^7$$NAME$$.");
	Lang("HU", "APPEAR_AFK",				"^7AFK^5-nak tϋnsz!");
	Lang("HU", "IS_AFK",					"$$NAME$$ ^7AFK^5-nak lαtszik!");
	Lang("HU", "MOVE_OR_KILL",				"^5Mozogj, vagy meg leszel ^7φlve!");
	Lang("HU", "ARTILLERY_NOT_AVAILABLE",	"TάZΙRSΙG nem elιrhetυ");
	Lang("HU", "PREDATOR_NOT_AVAILABLE",	"PREDΑTOR nem elιrhetυ");
	Lang("HU", "STRAFE_NOT_AVAILABLE",		"Strafe Run nem elιrhetυ");	
	Lang("HU", "PREDATOR_STAND",			"Αllnod kell, amikor Predαtort hνvsz!");
	Lang("HU", "PREDATOR_INCOMING",			"Predαtor ιrkezik");
	Lang("HU", "FRIENDLY_PREDATOR",			"Szφvegtsιges predαtor ιrkezik");
	Lang("HU", "ENEMY_PREDATOR",			"Ellensιges predαtor ιrkezik");
	Lang("HU", "ARTILLERY_INCOMING",		"Tόzιrsιget hνvva");
	Lang("HU", "FRIENDLY_ARTILLERY",		"Szφvetsιges tόzιrsιg hνvva");
	Lang("HU", "ENEMY_ARTILLERY",			"Ellensιges tόzιrsιg hνvva");
	Lang("HU", "STRAFE_INCOMING",			"Strafe Run ιrkezik");
	Lang("HU", "FRIENDLY_STRAFE",			"Szφvetsιges Strafe Run ιrkezik");
	Lang("HU", "ENEMY_STRAFE",				"Ellensιges Strafe Run ιrkezik");
	Lang("HU", "PACKAGE_INCOMING",			"Segιlycsomag ιrkezik");
	Lang("HU", "FRIENDLY_PACKAGE",			"Szφvetsιges Care Package ιrkezik");
	Lang("HU", "ENEMY_PACKAGE",				"Ellensιges Care Package ιrkezik");
	Lang("HU", "PACKAGE_POSITION",			"Nem kιrhetsz segιlycsomagot erre a pozνciσra");
	Lang("HU", "START_MAPVOTE",				"Nyomj Tϋz gombot a szavazαshoz");
	Lang("HU", "MAX_PRESTIGE",				"Elιrted a maximum presztizs szintet!");
	Lang("HU", "NOT_REACHED_LVL",			"Mιg nem ιrted el az 55 φs szintet");
	Lang("HU", "PRESTIGE_KILLS_LEFT",		"Mιg $$KILLS$$ φlιs van hαtra!");
	Lang("HU", "WELCOME",					"άdvφzlet");
	Lang("HU", "FRAG_WAIT",					"Vαrnod kell $$TIME$$ mαsodpercet");
	Lang("HU", "predator_mp",				"Nyomj [{+actionslot 4}]-t a PREDΑTOR-hoz.");
	Lang("HU", "artillery_mp",				"Nyomj [{+actionslot 4}]-t a TάZΙRSΙGHEZ");
	Lang("HU", "carepackage_mp",			"Nyomj [{+actionslot 4}]-t a SEGΙLYCSOMAGhoz");
	Lang("HU", "strafe_mp",					"Nyomj [{+actionslot 4}]-t Strafe Run hoz");	
	Lang("HU", "PICKUP",					"Nyomj ^3[[{+usereload}]] ^7hogy felvedd a segιlycsomagot");	
	Lang("HU", "NINJA",						"Ninja kιpessιged van!");	
	Lang("HU", "RUSHER",					"Rusher kιpessιged van!");	
	Lang("HU", "JUGGERNAUT",				"Juggernaut kιpessιged van!");	
	Lang("HU", "NUKE_BULLETS",				"Nuke tφltιnyeid vannak!");		
	Lang("HU", "ACCURACY",				 	&"^5Pontossαg:^7 &&1");	
	Lang("HU", "TRANSLATED_BY",				"Hungarian translation by Kubu");	
	//----------------------------POLISH---------------------------
	Lang("PL", "VIP_DM",					"DeathMachine ON/OFF");
	Lang("PL", "VIP_FREEZE",				"FreezeAll ON/OFF");
	Lang("PL", "VIP_INVIS",					"Invisible ON/OFF");
	Lang("PL", "VIP_PICKUP",				"Pickup ON/OFF");
	Lang("PL", "VIP_NUKEBULL",				"NukeBullets");
	Lang("PL", "VIP_DOGOD",					"GodMode On");
	Lang("PL", "VIP_NOVA",					"GAS Nade");
	Lang("PL", "VIP_ROCKNUKE",				"Rocket Nuke");
	Lang("PL", "VIP_JETPACK",				"Jetpack");
	Lang("PL", "VIP_TELEGUN",				"Telegun");
	Lang("PL", "VIP_AMMO",					"Ammo");
	
	Lang("PL", "YOUR_BOUNCED",           	"^5Zostales ^7podbity ^5przez Administratora");
	Lang("PL", "BOUNCED_NOTIFY",     		"$$CLANTAG$$[admin]: ^5Podbito ^7$$NAME$$.");
	Lang("PL", "APPEAR_AFK",               "^5Zdaje sie, ze jestes ^7AFK!");
	Lang("PL", "IS_AFK",           			"$$NAME$$ ^5wydaje sie byc ^7AFK!");
	Lang("PL", "MOVE_OR_KILL",            	"^5Rusz sie bo ^7zginiesz!");
	Lang("PL", "ARTILLERY_NOT_AVAILABLE", 	"ARTYLERIA niedostepnia");
	Lang("PL", "PREDATOR_NOT_AVAILABLE",  	"PREDATOR niedostepny");
	Lang("PL", "STRAFE_NOT_AVAILABLE",   	"OSTRZAL niedostepny");  
	Lang("PL", "PREDATOR_STAND",          	"Musisz stac aby uzyc rakiety Predator");
	Lang("PL", "PREDATOR_INCOMING",      	"Predator nadchodzi");
	Lang("PL", "FRIENDLY_PREDATOR",    		"Przyjacielski Predator nadchodz");
	Lang("PL", "ENEMY_PREDATOR",          	"Wrogi Predator nadchodzi");
 	Lang("PL", "ARTILLERY_INCOMING",     	"Artyleria nadchodzi");
 	Lang("PL", "FRIENDLY_ARTILLERY",    	"Przyjacielska artyleria nadchodzi");
	Lang("PL", "ENEMY_ARTILLERY",       	"Wroga artyleria nadchodzi");
	Lang("PL", "STRAFE_INCOMING",       	"Ostrzal nadchodzi");
	Lang("PL", "FRIENDLY_STRAFE", 			"Przyjacielski ostrzal nadchodzi");
	Lang("PL", "ENEMY_STRAFE",            	"Wrogi ostrzal nadchodzi");
	Lang("PL", "PACKAGE_INCOMING",        	"Paczka z zaopatrzeniem nadchodzi");
	Lang("PL", "FRIENDLY_PACKAGE",       	"Paczka z zaopatrzeniem nadchodzi");
	Lang("PL", "ENEMY_PACKAGE",          	"Wroga paczka z zaopatrzeniem nadchodzi");
	Lang("PL", "PACKAGE_POSITION",         	"Nie mozna zrzucic tutaj paczki z zaopatrzeniem");
	Lang("PL", "START_MAPVOTE",  			"Kliknij Strzal aby glosowac");
  	Lang("PL", "MAX_PRESTIGE",         		"Twoj poziom prestizu jest maksymalny!");
  	Lang("PL", "NOT_REACHED_LVL",        	"Nie osiagnoles jeszcze 55 poziomu");
  	Lang("PL", "PRESTIGE_KILLS_LEFT",     	"Zostalo $$KILLS$$ zabojstw!");
 	Lang("PL", "WELCOME",                  	"Witaj");
	Lang("PL", "FRAG_WAIT",             	"Musisz poczekac $$TIME$$ sekund");
	Lang("PL", "predator_mp",             	"Wcisnij [{+actionslot 4}] by wezwac PREDATOR");
	Lang("PL", "artillery_mp",            	"Wcisnij [{+actionslot 4}] by wezwac ARTYLERIE");
	Lang("PL", "carepackage_mp",       		"Wcisnij [{+actionslot 4}] by zrzucic ZAOPATRZENIE");
	Lang("PL", "strafe_mp",            		"Wcisnij [{+actionslot 4}] aby wezwac OSTRZAL");    
	Lang("PL", "PICKUP",               		"Wcisnij ^3[[{+usereload}]] ^7aby podniesc ZAOPATRZENIE");  
	Lang("PL", "NINJA",               		"Zdobyles zdolnosc: Ninja!");    
	Lang("PL", "RUSHER",               		"Zdobyles zdolnosc: Rusher!");    
	Lang("PL", "JUGGERNAUT",              	"Zdobyles zdolnosc: Juggernaut!");
	Lang("PL", "NUKE_BULLETS",            	"Dostales pociski jadrowe!");      
	Lang("PL", "ACCURACY",                	&"^5Celnosc:^7 &&1");
	Lang("PL", "CURRENT_HONOR",				&"Zgromadzono &&1 wyrσznienia.");
	Lang("PL", "HONOR_PLAYER",				&"Nacionij ^3[FLASH] ^7aby wyrσznic ^7&&1 za to zabσjstwo.");
	Lang("PL", "GOT_HONORED",				"Zosta³eo wyrσΏniony przez $$NAME$$");
	Lang("PL", "KILLED_PLAYER",				&"Zabiles &&1.");
	Lang("PL", "GOT_KILLED",				&"Zabity przez &&1.");	
	Lang("PL", "TRAINING_AREA",				"Nacisnij ^3[U―YJ] ^7aby przejsc do strefy szkolenia");
	Lang("PL", "ENEMY_NUKE",				"Wrogi Nuke nadchodzi");
	Lang("PL", "FRIENDLY_NUKE",				"Przyjacielski Nuke nadchodzi");
	Lang("PL", "NUKE_INCOMING",				"Nuke nadchodzi");
	Lang("PL", "NUKE_NOT_AVAILABLE",		"Nuke niedostepny");
	Lang("PL", "nuke_mp",					"Nacisnij [{+actionslot 4}] aby wezwac NUKE");
	Lang("PL", "SPAWN_PROTECTION",			&"Spawnprotection...^3&&1");
	Lang("PL", "REFLECT_ON",				"Obrazenia ^5aktywowane z powodu kampienia!");
	Lang("PL", "NO_PERMISSION",				"Nie masz uprawnien do korzystania z tej funkcji!\nBrak uprawnien: $$PERMISSION$$");
	Lang("PL", "PRESTIGE_UNLOCK",			"Musisz osiagnac poziom Prestige $$LEVEL$$ aby odblokowac $$FEATURE$$");
	Lang("PL", "MENU_NAVI",					"^7Wybierz: ^3[Prawy lub lewy przycisk myszy]^7\nUzyj: ^3[[{+activate}]]^7\nWyjdz: ^3[[{+melee}]]");
	Lang("PL", "HELP_TIME_LEFT",			&"&&1 sekund pozostalo do zamkniecia!");
	Lang("PL", "HELP_CLOSE",				"Nacisnij ^3[[{+melee}]] ^7aby zamknac menu!");
	Lang("PL", "HELP_1",					"Ten server oferuje wiele nowych funkcji, aby poprawic\ndoznania podczas gry, dlatego jest tutaj menu, w ktσrym\nmozesz zmienic niektσre ustawienia graficzne.\nMozesz je otworzyc za pomoca podwσjnego nacisniccia przycisku noktowizora");
	Lang("PL", "HELP_2",					"lub wpisujac '!menu' na czacie.\nTekst emblematu moze zostac zmieniony przy uzyciu:\n!emblem <TWΣJ TEKST>");
	Lang("PL", "TRANSLATED_BY",				"Polish translation by Myst and BraXi");	
	Lang("PL", "REAPER",					"prasa [{+actionslot 4}] dla zniwiarz");
	Lang("PL", "REAPER_NOT_AVAILABLE",		"zniwiarz nie dostepny");
	Lang("PL", "REAPER_INCOMING",				"zniwiarz przybywajacy");
	Lang("PL", "FRIENDLY_REAPER",				"przyjazny zniwiarz przybywajacy");
	Lang("PL", "ENEMY_REAPER",				"wrσg zniwiarz przybywajacy");
	//---------------------------DUTCH------------------------
	Lang("NL", "VIP_DM",					"DeathMachine ON/OFF");
	Lang("NL", "VIP_FREEZE",				"FreezeAll ON/OFF");
	Lang("NL", "VIP_INVIS",					"Invisible ON/OFF");
	Lang("NL", "VIP_PICKUP",				"Pickup ON/OFF");
	Lang("NL", "VIP_NUKEBULL",				"NukeBullets");
	Lang("NL", "VIP_DOGOD",					"GodMode On");
	Lang("NL", "VIP_NOVA",					"GAS Nade");
	Lang("NL", "VIP_ROCKNUKE",				"Rocket Nuke");
	Lang("NL", "VIP_JETPACK",				"Jetpack");
	Lang("NL", "VIP_TELEGUN",				"Telegun");
	Lang("NL", "VIP_AMMO",					"Ammo");
	
	Lang("NL", "REAPER",					"Druk op de knop [{+actionslot 4}] voor de Reaper");
	Lang("NL", "REAPER_NOT_AVAILABLE",		"Reaper is niet beschikbaar momenteel");
	Lang("NL", "REAPER_INCOMING",				"Reaper inkomend");
	Lang("NL", "FRIENDLY_REAPER",				"Vriendelijke Reaper inkomend");
	Lang("NL", "ENEMY_REAPER",				"Vijandelijke Reaper inkomend");
	Lang("NL", "YOUR_BOUNCED",             	"^5Je bent ^7gebounced ^5door een Admin");
	Lang("NL", "BOUNCED_NOTIFY",           	"$$CLANTAG$$[admin]: ^5heeft ^7$$NAME$$ Gebounced.");
	Lang("NL", "APPEAR_AFK",         		"^5Je blijkt niet ^7actief&5 te zijn!");
	Lang("NL", "IS_AFK",                   	"$$NAME$$ ^5blijkt niet actief te zijn!");
  	Lang("NL", "MOVE_OR_KILL",            	"^5Beweeg of je word ^7gedood!");
	Lang("NL", "ARTILLERY_NOT_AVAILABLE",	"ARTILLERY niet beschikbaar");
	Lang("NL", "PREDATOR_NOT_AVAILABLE",  	"PREDATOR niet beschikbaar");
	Lang("NL", "STRAFE_NOT_AVAILABLE",     	"Strafe Run niet beschikbaar");   
	Lang("NL", "PREDATOR_STAND",          	"Je moet staan als je Predator wilt gebruiken");
	Lang("NL", "PREDATOR_INCOMING",       	"Er komt een Predator aan");
	Lang("NL", "FRIENDLY_PREDATOR",        	"Er komt een Predator van een teamgenoot aan");
	Lang("NL", "ENEMY_PREDATOR",        	"Er komt een Vijandelijke Predator aan");
	Lang("NL", "ARTILLERY_INCOMING",    	"Artillery staat klaar");
	Lang("NL", "FRIENDLY_ARTILLERY",      	"Artillery van een teamgenoot staat klaar");
	Lang("NL", "ENEMY_ARTILLERY",         	"Vijandelijke Artillery staat klaar");
	Lang("NL", "STRAFE_INCOMING",         	"Er komt een Strafe Run aan");
	Lang("NL", "FRIENDLY_STRAFE",        	"Er komt een Strafe Run van een teamgenoot aan");
	Lang("NL", "ENEMY_STRAFE",            	"Er komt een Vijandelijke Strafe Run aan");
	Lang("NL", "PACKAGE_INCOMING",        	"Er komt een Care Package aan");
 	Lang("NL", "FRIENDLY_PACKAGE",         	"Er komt een Care Package van een teamgenoot aan");
	Lang("NL", "ENEMY_PACKAGE",           	"Er komt een Vijandelijke Care Package aan");
	Lang("NL", "PACKAGE_POSITION",       	"Je kan geen Care Package oproepen vanaf deze positie");
 	Lang("NL", "START_MAPVOTE",            	"Druk Schieten om te stemmen");
	Lang("NL", "MAX_PRESTIGE",           	"Je hebt al het maximale prestige level bereikt!");
	Lang("NL", "NOT_REACHED_LVL",          	"Je hebt nog niet level 55 bereikt");
	Lang("NL", "PRESTIGE_KILLS_LEFT",      	"Nog $$KILLS$$ kills te gaan!");
  	Lang("NL", "WELCOME",					"Goedendag");
	Lang("NL", "FRAG_WAIT", 				"Je moet nog $$TIME$$ seconden wachten");
	Lang("NL", "predator_mp",        		"Druk [{+actionslot 4}] voor PREDATOR");
 	Lang("NL", "artillery_mp",            	"Druk [{+actionslot 4}] voor ARTILLERY");
	Lang("NL", "carepackage_mp",           	"Druk [{+actionslot 4}] voor CARE PACKAGE");
	Lang("NL", "strafe_mp",          		"Druk [{+actionslot 4}] voor Strafe Run");     
	Lang("NL", "PICKUP",              		"Druk ^3[[{+usereload}]] ^7om je Carepackage te pakken");   
	Lang("NL", "NINJA",                  	"Je hebt de vaardigheid Ninja verkregen!");     
	Lang("NL", "RUSHER",               		"Je hebt de vaardigheid Rusher verkregen!");    
	Lang("NL", "JUGGERNAUT",        		"Je hebt de vaardigheid Juggernaut verkregen!");
	Lang("NL", "NUKE_BULLETS",           	"Je hebt de vaardigheid Nuke bullets verkregen!");      
	Lang("NL", "ACCURACY",                	&"^5Precisie :^7 &&1");	
	Lang("NL", "HELP_1",					"Deze server bied vele nieuwe opties om jouw\ngame ervaring te verbeteren, er is een menu\nwaar je prestige kan gaan of je graphics veranderen.\nJe kan het openen door 2x op Nightvision te drukken\nof door '!menu' te typen in de chat."); // THIS TEXT MUST BE SHORTER THEN 256 chars
    Lang("NL", "HELP_2",           			"Je emblemtekst kan worden veranderd door het volgende te typen:\n!emblem <YOUR TEXT>");
    Lang("NL", "HELP_CLOSE",              	"Druk ^3[[{+melee}]] ^7om dit menu te sluiten!");
    Lang("NL", "HELP_TIME_LEFT",          	&"&&1 tot je het scherm kan sluiten!");
    Lang("NL", "MENU_NAVI",             	"^7Selecteer: ^3[Rechter of Linker muisknop]^7\nOpen of Gebruik: ^3[[{+activate}]]^7\nVerlaten: ^3[[{+melee}]]");
    Lang("NL", "PRESTIGE_UNLOCK",        	"Je moet Prestige level $$LEVEL$$ zijn om $$FEATURE$$ te unlocken");
    Lang("NL", "NO_PERMISSION",           	"Je hebt geen rechten om dit te gebruiken!\nToegang gewijgerd: $$PERMISSION$$");
    Lang("NL", "REFLECT_ON",              	"Schade Reflectie ^5geactiveerd omdat je camped!");
    Lang("NL", "SPAWN_PROTECTION",        	&"Spawnprotectie...^3&&1");
 	Lang("NL", "nuke_mp",					"Druk [{+actionslot 4}] voor NUKE");
	Lang("NL", "NUKE_NOT_AVAILABLE",		"Nuke niet beschikbaar");	
	Lang("NL", "NUKE_INCOMING",				"Er komt een Nuke aan");
	Lang("NL", "FRIENDLY_NUKE",				"Een Teamgenoot heeft een Nuke opgeroepen");
	Lang("NL", "ENEMY_NUKE",				"Vijandelijke Nuke in aantocht"); 
	Lang("NL", "CURRENT_HONOR",				&"Verzamel &&1 zijn eer.");
	Lang("NL", "HONOR_PLAYER",				&"Druk ^3[FLASH] ^7om ^7&&1 eer te geven voor zijn kill.");
	Lang("NL", "GOT_HONORED",				"Je hebt eer gekregen van $$NAME$$");
	Lang("NL", "KILLED_PLAYER",				&"Je hebt &&1 gedood.");
	Lang("NL", "GOT_KILLED",				&"Gedood door &&1.");	
	Lang("NL", "TRAINING_AREA",				"Druk ^3[USE] ^7om het trainingsgebied in te gaan.");
	Lang("NL", "CURRENT_HONOR",				&"Verzamel &&1 zijn eer.");
	Lang("NL", "HONOR_PLAYER",				&"Druk ^3[FLASH] ^7om ^7&&1 eer te geven voor zijn kill.");
	Lang("NL", "GOT_HONORED",				"Je hebt eer gekregen van $$NAME$$");
	Lang("NL", "KILLED_PLAYER",				&"Je hebt &&1 gedood.");
	Lang("NL", "GOT_KILLED",				&"Gedood door &&1.");	
	Lang("NL", "TRAINING_AREA",				"Druk ^3[USE] ^7om het trainingsgebied in te gaan.");	
	Lang("NL", "TRANSLATED_BY",				"Dutch translation by Wingzor");	  
	//-------------------------ITALIAN-------------------------
	Lang("IT", "VIP_DM",					"DeathMachine ON/OFF");
	Lang("IT", "VIP_FREEZE",				"FreezeAll ON/OFF");
	Lang("IT", "VIP_INVIS",					"Invisible ON/OFF");
	Lang("IT", "VIP_PICKUP",				"Pickup ON/OFF");
	Lang("IT", "VIP_NUKEBULL",				"NukeBullets");
	Lang("IT", "VIP_DOGOD",					"GodMode On");
	Lang("IT", "VIP_NOVA",					"GAS Nade");
	Lang("IT", "VIP_ROCKNUKE",				"Rocket Nuke");
	Lang("IT", "VIP_JETPACK",				"Jetpack");
	Lang("IT", "VIP_TELEGUN",				"Telegun");
	Lang("IT", "VIP_AMMO",					"Ammo");
	
	Lang("IT", "REAPER",					"Press [{+actionslot 4}] per Reaper");
	Lang("IT", "REAPER_NOT_AVAILABLE",		"Reaper non disponibile");
	Lang("IT", "REAPER_INCOMING",				"Reaper in arrivo");
	Lang("IT", "FRIENDLY_REAPER",				"amichevole Reaper in arrivo");
	Lang("IT", "ENEMY_REAPER",				"nemico Reaper in arrivo");
	Lang("IT", "YOUR_BOUNCED",				"^5Sei ^7stato rimbalzato ^5Dall'Admin");
	Lang("IT", "BOUNCED_NOTIFY",			"$$CLANTAG$$[admin]: ^5Ha Rimbalzato ^7$$NAME$$.");
	Lang("IT", "APPEAR_AFK",				"^5Sembra che tu sia ^7AFK!");
	Lang("IT", "IS_AFK",					"$$NAME$$ ^5Sembra che sia ^7AFK!");
	Lang("IT", "MOVE_OR_KILL",				"^5Muoviti o verrai ^7ucciso!");
	Lang("IT", "ARTILLERY_NOT_AVAILABLE",	"Artiglieria non disponibile");
	Lang("IT", "PREDATOR_NOT_AVAILABLE",	"Predator non disponibile");
	Lang("IT", "STRAFE_NOT_AVAILABLE",		"Strafe Run non disponibile");	
	Lang("IT", "PREDATOR_STAND",			"Devi stare fermo mentre usi il Predator");
	Lang("IT", "PREDATOR_INCOMING",			"Predator in arrivo");
	Lang("IT", "FRIENDLY_PREDATOR",			"Predator alleato in arrivo");
	Lang("IT", "ENEMY_PREDATOR",			"Predator nemico in arrivo");
	Lang("IT", "ARTILLERY_INCOMING",		"Artiglieria in attesa");
	Lang("IT", "FRIENDLY_ARTILLERY",		"Artiglieria alleata in attesa");
	Lang("IT", "ENEMY_ARTILLERY",			"Artiglieria nemica in attesa");
	Lang("IT", "STRAFE_INCOMING",			"Strafe Run in arrivo");
	Lang("IT", "FRIENDLY_STRAFE",			"Strafe Run alleato in arrivo");
	Lang("IT", "ENEMY_STRAFE",				"Strafe Run nemico in arrivo");
	Lang("IT", "PACKAGE_INCOMING",			"Approvigionamento in arrivo");
	Lang("IT", "FRIENDLY_PACKAGE",			"Approvigionamento alleato in arrivo");
	Lang("IT", "ENEMY_PACKAGE",				"Approvigionamento nemico in arrivo");
	Lang("IT", "PACKAGE_POSITION",			"Non puoi chiamare gl' approvigionamenti da questa posizione");
	Lang("IT", "START_MAPVOTE",				"premi Fuoco per votare");
	Lang("IT", "MAX_PRESTIGE",				"Tu sei giΰ al livello di prestigio massimo!");
	Lang("IT", "NOT_REACHED_LVL",			"Non hai ancora raggiunto il livello 55");
	Lang("IT", "PRESTIGE_KILLS_LEFT",		"Ci sono ancora $$KILLS$$ uccisioni rimaste!");
	Lang("IT", "WELCOME",					"Benvenuto!");
	Lang("IT", "FRAG_WAIT",					"Devi aspettare $$TIME$$ secondi");
	Lang("IT", "predator_mp",				"Premi [{+actionslot 4}] per PREDATOR");
	Lang("IT", "artillery_mp",				"Premi [{+actionslot 4}] per ARTiGLIERIA");
	Lang("IT", "carepackage_mp",			"Premi [{+actionslot 4}] per APPROVIGIONAMENTO");
	Lang("IT", "strafe_mp",					"Premi [{+actionslot 4}] per Strafe Run");	
	Lang("IT", "PICKUP",					"Premi ^3[[{+usereload}]] ^7per raccogliere l' APPROVIGIONAMENTO");	
	Lang("IT", "NINJA",						"Tu hai preso l'abilitΰ Ninja!");	
	Lang("IT", "RUSHER",					"Tu hai preso l'abilitΰ Corridore!");	
	Lang("IT", "JUGGERNAUT",				"Tu hai preso l'abilitΰ Juggernaut!");	
	Lang("IT", "NUKE_BULLETS",				"Tu hai preso i proiettili Nucleari!");	
	Lang("IT", "ACCURACY",				 	&"^5Accuratezza:^7 &&1");
	Lang("IT", "HELP_1",					"Questo Server offre molte nuove opzioni per migliorare la tua\nesperienza di gioco, per questo c'θ un Menu dove tu\npuoi prestigiare e cambiare un pς di settings Grafici.\nPuς essere aperto premendo Due volte il bottone per la Visione Notturna"); // THIS TEXT MUST BE SHORTER THEN 256 chars
	Lang("IT", "HELP_2",					"o scrivendo '!menu' nella chat.\nL' emblemtext puς essere cambiato scrivendo:\n!emblem <TUO TESTO>");
	Lang("IT", "HELP_CLOSE",				"Premi ^3[[{+melee}]] ^7Per chiudere questo menu!");
	Lang("IT", "HELP_TIME_LEFT",			&"&&1 Secondi rimanenti prima che tu possa chiudere!");
	Lang("IT", "MENU_NAVI",					"^7Seleziona: ^3[Destra o Sinistra del Mouse]^7\nUsa: ^3[[{+activate}]]^7\nEsci: ^3[[{+melee}]]");
	Lang("IT", "PRESTIGE_UNLOCK",			"Tu devi arrivare al livello prestigio $$LEVEL$$ Per sbloccare $$FEATURE$$");
	Lang("IT", "NO_PERMISSION",				"Non hai il permesso di usarlo!\nErrore nei Permessi: $$PERMISSION$$");
	Lang("IT", "REFLECT_ON",				"Danno Refletto ^5attivato perchθ camperi!");
	Lang("IT", "SPAWN_PROTECTION",			&"Protezione Spawn...^3&&1");
	Lang("IT", "nuke_mp",					"Premi [{+actionslot 4}] per Bomba Nucleare");
	Lang("IT", "NUKE_NOT_AVAILABLE",		"Bomba Nucleare non disponibile");	
	Lang("IT", "NUKE_INCOMING",				"Bomba Nucleare in arrivo");
	Lang("IT", "FRIENDLY_NUKE",				"Bomba Nucleare alleata in arrivo");
	Lang("IT", "ENEMY_NUKE",				"Bomba Nucleare nemica in arrivo");		
	Lang("IT", "TRAINING_AREA",				"Premi ^3[USE] ^7per entrare nel campo d'addestramento");
	Lang("IT", "GOT_KILLED",				&"Ucciso da &&1.");	
	Lang("IT", "KILLED_PLAYER",				&"Hai ucciso &&1.");
	Lang("IT", "GOT_HONORED",				"Sei stato onorato da $$NAME$$");
	Lang("IT", "HONOR_PLAYER",				&"Premi ^3[FLASH] ^7per onorare ^7&&1 per questa Uccisione.");
	Lang("IT", "CURRENT_HONOR",				&"Collezionati &&1 onouri.");
	Lang("IT", "MENU_PRESTIGE",				"Prestigia");
	Lang("IT", "MENU_LASER",				"Dis-/Abilita Laser Prstg 3");
	Lang("EN", "MENU_THERMAL",				"Toggle Thermal (Prestige 2)");
	Lang("IT", "MENU_EMBLEM",				"Cambia emblema Prstg 1");
	Lang("IT", "MENU_EMBLEM_DEFAULT",		"Design originale");
	Lang("IT", "MENU_EMBLEM_BLUE",			"Design Blu");
	Lang("IT", "MENU_EMBLEM_RED",			"Design Rosso");
	Lang("IT", "MENU_EMBLEM_GREEN",			"Design Verde");
	Lang("IT", "MENU_EMBLEM_YELLOW",		"giallo Design");
	Lang("IT", "MENU_EMBLEM_ADMIN",			"RS-Membro Design");
	Lang("IT", "MENU_EMBLEM_OWN",			"Invia il tuo tema");
	Lang("IT", "MENU_EMBLEM_3RS",			"Stile ^1RS^7'");
	Lang("IT", "MENU_FILM",					"Seleziona filmtweaks");
	Lang("IT", "MENU_TWEAK",				"Tweaks");
	Lang("IT", "MENU_BRIGHT",				"Dis-/Abilita fullbright");
	Lang("IT", "MENU_FOG",					"Dis-/Abilita nebbia");
	Lang("IT", "MENU_LASER2",				"Dis-/Abilita laser");
	Lang("IT", "MENU_RULES",				"Cambia gamerules");
	Lang("IT", "MENU_RESET",				"Reset Completo");
	Lang("IT", "MENU_TWEAKS",				"Dis-/Abilita Filmtweaks");
	Lang("IT", "MENU_DEV",					"Sezione Admin");
	Lang("IT", "MENU_VIP",					"Vip section");
	Lang("IT", "RESPAWN_IN",				&"Respawn tra: &&1");
	Lang("IT", "TRANSLATED_BY",				"Tradotto da produde99 AKA Scary");
	//-------------------------FRENCH-------------------------
	Lang("FR", "VIP_DM",					"DeathMachine ON/OFF");
	Lang("FR", "VIP_FREEZE",				"FreezeAll ON/OFF");
	Lang("FR", "VIP_INVIS",					"Invisible ON/OFF");
	Lang("FR", "VIP_PICKUP",				"Pickup ON/OFF");
	Lang("FR", "VIP_NUKEBULL",				"NukeBullets");
	Lang("FR", "VIP_DOGOD",					"GodMode On");
	Lang("FR", "VIP_NOVA",					"GAS Nade");
	Lang("FR", "VIP_ROCKNUKE",				"Rocket Nuke");
	Lang("FR", "VIP_JETPACK",				"Jetpack");
	Lang("FR", "VIP_TELEGUN",				"Telegun");
	Lang("FR", "VIP_AMMO",					"Ammo");
	
	Lang("FR", "REAPER_NOT_AVAILABLE",		"Reaper pas disponible");
	Lang("FR", "REAPER_INCOMING",				"Reaper nouveau");
	Lang("FR", "FRIENDLY_REAPER",				"amical Reaper nouveau");
	Lang("FR", "ENEMY_REAPER",				"ennemi Reaper nouveau");
	Lang("FR", "YOUR_BOUNCED", 				"^5Vous avez ιtι ^7bouncι ^5par un Admin");
	Lang("FR", "BOUNCED_NOTIFY",			"$$CLANTAG$$[admin]: ^5a bouncι ^7$$NAME$$.");
	Lang("FR", "APPEAR_AFK", 				"^5Vous semblez κtre ^7absent!");
	Lang("FR", "IS_AFK", 					"$$NAME$$ ^5semble κtre ^7absent !");
	Lang("FR", "MOVE_OR_KILL", 				"^5Bougez ou vous serez ^7tuι !");
	Lang("FR", "ARTILLERY_NOT_AVAILABLE", 	"Artillerie non disponible");
	Lang("FR", "PREDATOR_NOT_AVAILABLE", 	"Missile Predator non disponible");
	Lang("FR", "STRAFE_NOT_AVAILABLE", 		"Helicoptθre Strafe Run non disponible");
	Lang("FR", "PREDATOR_STAND", 			"Vous devez vous lever pour utiliser le Predator");
	Lang("FR", "PREDATOR_INCOMING", 		"Missile Predator en approche");
	Lang("FR", "FRIENDLY_PREDATOR", 		"Missile Predator alliι en approche");
	Lang("FR", "ENEMY_PREDATOR", 			"Missile Predator ennemi en approche");
	Lang("FR", "ARTILLERY_INCOMING", 		"Artillerie en approche");
	Lang("FR", "FRIENDLY_ARTILLERY", 		"Artillerie alliιe en approche");
	Lang("FR", "ENEMY_ARTILLERY", 			"Artillerie ennemie en approche");
	Lang("FR", "STRAFE_INCOMING", 			"Hιlicoptθre Strafe Run en approche");
	Lang("FR", "FRIENDLY_STRAFE", 			"Hιlicoptθre Strafe Run alliι en approche");
	Lang("FR", "ENEMY_STRAFE", 				"Hιlicoptθre Strafe Run ennemi en approche");
	Lang("FR", "PACKAGE_INCOMING", 			"Colis stratιgique en approche");
	Lang("FR", "FRIENDLY_PACKAGE", 			"Colis stratιgique alliι en approche");
	Lang("FR", "ENEMY_PACKAGE", 			"Colis stratιgique ennemi en approche");
	Lang("FR", "PACKAGE_POSITION", 			"Vous ne pouvez pas appeler un colis stratιgique ΰ cet emplacement");
	Lang("FR", "START_MAPVOTE", 			"Appuyez sur la touche tirer pour voter");
	Lang("FR", "MAX_PRESTIGE", 				"Vous avez dιjΰ atteint le prestige max!");
	Lang("FR", "NOT_REACHED_LVL", 			"Vous n'avez pas encore atteint le niveau 55");
	Lang("FR", "PRESTIGE_KILLS_LEFT", 		"Il vous manque encore $$KILLS$$ kills!");
	Lang("FR", "WELCOME", 					"Bienvenue");
	Lang("FR", "FRAG_WAIT", 				"Vous devez attendre $$TIME$$ secondes");
	Lang("FR", "predator_mp", 				"Appuyez sur [{+actionslot 4}] pour un missile Predator");
	Lang("FR", "artillery_mp", 				"Appuyez sur [{+actionslot 4}] pour l'artillerie");
	Lang("FR", "carepackage_mp", 			"Appuyez sur [{+actionslot 4}] pour un colis stratιgique");
	Lang("FR", "strafe_mp", 				"Appuyez sur [{+actionslot 4}] pour un hιlicoptθre Strafe Run");
	Lang("FR", "PICKUP", 					"Appuyez sur ^3[[{+usereload}]] ^7pour prendre le colis stratιgique");
	Lang("FR", "NINJA", 					"Vous avez obtenu la compιtence Ninja!");
	Lang("FR", "RUSHER", 					"Vous avez obtenu la compιtence Rusher!");
	Lang("FR", "JUGGERNAUT", 				"Vous avez obtenu la compιtence Mastodonte!");
	Lang("FR", "NUKE_BULLETS", 				"Vous avez obtenu des balles nuclιaires");
	Lang("FR", "ACCURACY", 					&"^5Prιcision:^7 &&1");
	Lang("FR", "HELP_1", 					"Il y a un menu oω vous\npourrez augmenter votre prestige et changer plusieurs options graphiques.\nCela peut κtre ouvert en appuyant sur le bouton VISION NOCTURE deux fois\nou en tapant !menu dans le chat");
	Lang("FR", "HELP_2", 					"Votre texte d'emblθme peut κtre changι en tapant\n!emblem <VOTRE TEXTE>");
	Lang("FR", "HELP_CLOSE", 				"Appuyez sur ^3[[{+melee}]] ^7pour fermer ce menu!");
	Lang("FR", "HELP_TIME_LEFT", 			&"&&Il reste 1 seconde avant de pouvoir fermer!");
	Lang("FR", "MENU_NAVI", 				"^7Choisir: ^3[Clic droit ou gauche]^7\nUtiliser: ^3[[{+activate}]]^7\nSortir: ^3[[{+melee}]]"); //[RIGHT OR LEFT MOUSE] MUST BE CHANGED OR NO ?
	Lang("FR", "PRESTIGE_UNLOCK", 			"Vous devez atteindre le prestige $$LEVEL$$ pour dιvιrouiller $$FEATURE$$");
	Lang("FR", "NO_PERMISSION", 			"Vous n'avez pas les droits pour l'utiliser.\nEchec sur le droit : $$PERMISSION$$");
	Lang("FR", "REFLECT_ON", 				"Perte de santι ^5activιe pour avoir campι!");
	Lang("FR", "SPAWN_PROTECTION", 			&"Vous ne pouvez pas κtre tuι pendant ^3&&1");
	Lang("FR", "nuke_mp", 					"Appuyez sur [{+actionslot 4}] pour la bombe nuclιaire!");
	Lang("FR", "NUKE_NOT_AVAILABLE", 		"Bombe nuclιaire non disponible");
	Lang("FR", "NUKE_INCOMING", 			"Bombe nuclιaire en approche");
	Lang("FR", "FRIENDLY_NUKE", 			"Bombe nuclιaire alliιe en approche");
	Lang("FR", "ENEMY_NUKE", 				"Bombe nuclιaire ennemie en approche");
	Lang("FR", "TRAINING_AREA", 			"Appuyez sur ^3[UTILISER] ^7pour entrer dans l'arθne d'entraξnement");
	Lang("FR", "GOT_KILLED", 				&"Tuι par &&1.");
	Lang("FR", "KILLED_PLAYER",				&"Vous avez tuι &&1.");
	Lang("FR", "GOT_HONORED", 				"Vous avez ιtι honorι par $$NAME$$");
	Lang("FR", "HONOR_PLAYER", 				&"Appuyez sur ^3[FLASH] ^7pour honorer ^7&&1 pour ce kill");
	Lang("FR", "CURRENT_HONOR", 			&"Vous avez collectι &&1 mιdaille(s) d'honneur.");
	Lang("FR", "MENU_PRESTIGE", 			"Passer au prestige supιrieur");
	Lang("FR", "MENU_LASER", 				"Allumer/ιteindre le laser (Prestige 3)");
	Lang("EN", "MENU_THERMAL",				"Toggle Thermal (Prestige 2)");
	Lang("FR", "MENU_EMBLEM", 				"Changer d'emblθme (Prestige 1)");
	Lang("FR", "MENU_EMBLEM_DEFAULT",		"Style par dιfault");
	Lang("FR", "MENU_EMBLEM_BLUE", 			"Style bleu");
	Lang("FR", "MENU_EMBLEM_RED", 			"Style rouge");
	Lang("FR", "MENU_EMBLEM_GREEN", 		"Style vert");
	Lang("FR", "MENU_EMBLEM_YELLOW",		"Style jaune");
	Lang("FR", "MENU_EMBLEM_ADMIN",			"RS-Membre Design");
	Lang("FR", "MENU_EMBLEM_OWN", 			"Soumettre votre propre thθme");
	Lang("FR", "MENU_EMBLEM_3RS", 			"^5Style ^1RS' ");
	Lang("FR", "MENU_FILM", 				"Sιlectionnez un mode de vision");
	Lang("FR", "MENU_TWEAK", 				"Modifications");
	Lang("FR", "MENU_BRIGHT", 				"Activer/dιsactiver la luminositι max");
	Lang("FR", "MENU_FOG", 					"Activer/dιsactiver le brouillard");
	Lang("FR", "MENU_LASER2", 				"Activer/dιsactiver le laser");
	Lang("FR", "MENU_RULES", 				"Changer les rθgles");
	Lang("FR", "MENU_RESET", 				"Tout rιinitialiser");
	Lang("FR", "MENU_TWEAKS", 				"Activer/dιsactiver le mode de vision");
	Lang("FR", "MENU_DEV", 					"Section des admins");
	Lang("FR", "MENU_VIP",					"Vip section");
	Lang("FR", "TRANSLATED_BY", 			"Traduction Franηaise par Aurel004");
	//-------------------------NORWAY-------------------------
	Lang("NO", "VIP_DM",					"DeathMachine ON/OFF");
	Lang("NO", "VIP_FREEZE",				"FreezeAll ON/OFF");
	Lang("NO", "VIP_INVIS",					"Invisible ON/OFF");
	Lang("NO", "VIP_PICKUP",				"Pickup ON/OFF");
	Lang("NO", "VIP_NUKEBULL",				"NukeBullets");
	Lang("NO", "VIP_DOGOD",					"GodMode On");
	Lang("NO", "VIP_NOVA",					"GAS Nade");
	Lang("NO", "VIP_ROCKNUKE",				"Rocket Nuke");
	Lang("NO", "VIP_JETPACK",				"Jetpack");
	Lang("NO", "VIP_TELEGUN",				"Telegun");
	Lang("NO", "VIP_AMMO",					"Ammo");
	
	Lang("NO", "REAPER",					"Press [{+actionslot 4}] for Reaper");
	Lang("NO", "REAPER_NOT_AVAILABLE",		"Reaper ikke tilgjengelig");
	Lang("NO", "REAPER_INCOMING",				"Reaper innkommende");
	Lang("NO", "FRIENDLY_REAPER",				"vennlig Reaper innkommende");
	Lang("NO", "ENEMY_REAPER",				"Enemy Reaper innkommende");
    Lang("NO", "YOUR_BOUNCED",				"^5Du ble ^7bouncet ^5av en Admin");
    Lang("NO", "BOUNCED_NOTIFY",			"$$CLANTAG$$[admin]: ^5Bouncet ^7$$NAME$$.");
    Lang("NO", "APPEAR_AFK",				"^5Det ser ut som du er ^7AFK!");
    Lang("NO", "IS_AFK",					"$$NAME$$ ^5ser ut som er ^7AFK!");
    Lang("NO", "MOVE_OR_KILL",				"^5Flytt deg eller bli ^7drept!");
    Lang("NO", "ARTILLERY_NOT_AVAILABLE",   "Artillery er ikke tilgjengelig");
    Lang("NO", "PREDATOR_NOT_AVAILABLE",    "Predator er ikke tilgjengelig");
    Lang("NO", "STRAFE_NOT_AVAILABLE",		"Strafe Run er ikke tilgjengelig");      
    Lang("NO", "PREDATOR_STAND",			"Du mε stε mens du bruker Predator");
    Lang("NO", "PREDATOR_INCOMING",			"Predator innkommer!");
    Lang("NO", "FRIENDLY_PREDATOR",			"Vennelig Predator kommer");
    Lang("NO", "ENEMY_PREDATOR",			"Fiende Predator kommer");
    Lang("NO", "ARTILLERY_INCOMING",		"Artillery stεr ved");
    Lang("NO", "FRIENDLY_ARTILLERY",		"Vennelig Artillery stεr ved");
    Lang("NO", "ENEMY_ARTILLERY",			"Fiende Artillery stεr ved");
    Lang("NO", "STRAFE_INCOMING",			"Strafe Run kommer");
    Lang("NO", "FRIENDLY_STRAFE",           "Vennelig Strafe Run kommer");
    Lang("NO", "ENEMY_STRAFE",				"Fiende Strafe Run kommer");
    Lang("NO", "PACKAGE_INCOMING",			"Care Package kommer");
    Lang("NO", "FRIENDLY_PACKAGE",			"Vennelig Care Package kommer");
    Lang("NO", "ENEMY_PACKAGE",				"Fiende Care Package kommer");
    Lang("NO", "PACKAGE_POSITION",			"Du kan ikke kalle en Care Package pε denne posisjonen");
    Lang("NO", "START_MAPVOTE",				"Trykk Fire til ε Stemme");
    Lang("NO", "MAX_PRESTIGE",				"Du har allerede komt til maks prestige level!");
    Lang("NO", "NOT_REACHED_LVL",			"Du har ikke komt i lv 55 enda");
    Lang("NO", "PRESTIGE_KILLS_LEFT",		"Det er enda $$KILLS$$ kills igjen!");
    Lang("NO", "WELCOME",					"Velkommen");
    Lang("NO", "FRAG_WAIT",					"Du mε vente $$TIME$$ sekunder");
    Lang("NO", "predator_mp",				"Trykk [{+actionslot 4}] for PREDATOR");
    Lang("NO", "artillery_mp",				"Trykk [{+actionslot 4}] for ARTILLERY");
    Lang("NO", "carepackage_mp",			"Trykk [{+actionslot 4}] for CARE PACKAGE");
    Lang("NO", "strafe_mp",					"Trykk [{+actionslot 4}] for Strafe Run");       
    Lang("NO", "PICKUP",					"Trykk ^3[[{+usereload}]] ^7til ε plukke opp Carepackagen");  
    Lang("NO", "NINJA",						"Du fikk evne Ninja!");
    Lang("NO", "RUSHER",					"Du fikk evne Rusher!");       
    Lang("NO", "JUGGERNAUT",				"Du fikk evne Juggernaut!");   
    Lang("NO", "NUKE_BULLETS",				"Du fikk Nuke bullets!");      
    Lang("NO", "ACCURACY",					&"^5Nψyaktighet:^7 &&1");
    Lang("NO", "HELP_1",					"Denne Serveren tilbyr mange nye funksjoner til ε forbedre \ngamingen din, derfor er det en Meny der du\nkan komme i prestige og endre grafikk settingene.\nDu kan εpne den hvis du trykker Nightvision-knappen to ganger\neller skriv '!menu' i chatten."); // THIS TEXT MUST BE SHORTER THEN 256 chars
    Lang("NO", "HELP_2",					"Emblemteksten kan bli forandred hvis du skriver:\n!emblem <DIN TEKST>");
    Lang("NO", "HELP_CLOSE",				"Trykk ^3[[{+melee}]] ^7for ε lukke denne menyen!");
    Lang("NO", "HELP_TIME_LEFT",			&"&&1 sekunder igjen fψr du kan lukke!");
    Lang("NO", "MENU_NAVI",					"^7Velg: ^3[Hψyre Eller Venstre Mus]^7\nBruk: ^3[[{+activate}]]^7\nForlate: ^3[[{+melee}]]");
    Lang("NO", "PRESTIGE_UNLOCK",			"Du mε komme i Prestige level $$LEVEL$$ for ε unlocke $$FEATURE$$");
    Lang("NO", "NO_PERMISSION",				"Du har ingen avgang til ε bruke dette!\nFailet om tilgang: $$PERMISSION$$");
    Lang("NO", "REFLECT_ON",				"Skade refleksjon ^5aktivert pε grunn av camping!");
    Lang("NO", "SPAWN_PROTECTION",			&"Spawnsikkerhet...^3&&1");
    Lang("NO", "nuke_mp",					"Trykk [{+actionslot 4}] for NUKE");
    Lang("NO", "NUKE_NOT_AVAILABLE",		"Nuke er ikke tilgjengelig");  
    Lang("NO", "NUKE_INCOMING",				"Nuke kommer");
    Lang("NO", "FRIENDLY_NUKE",				"Vennelig Nuke kommer");
    Lang("NO", "ENEMY_NUKE",				"Fiende Nuke kommer");         
    Lang("NO", "TRAINING_AREA",				"Trykk ^3[BRUK] ^7for ε komme til Trenings Omrεde");
    Lang("NO", "GOT_KILLED",				&"Drept av &&1.");     
    Lang("NO", "KILLED_PLAYER",				&"Du drepte &&1.");
    Lang("NO", "GOT_HONORED",				"Du har blitt ζret av $$NAME$$");
    Lang("NO", "HONOR_PLAYER",				&"Trykk ^3[FLASH] ^7for ε ζre ^7&&1 for denne killen");
    Lang("NO", "CURRENT_HONOR",				&"Samlet&&1 ζrer.");
    Lang("NO", "TRANSLATED_BY",				"Norwegian translation by Amitoz");
	//-------------------------GREEK--------------------------
	Lang("GR", "VIP_DM",					"DeathMachine ON/OFF");
	Lang("GR", "VIP_FREEZE",				"FreezeAll ON/OFF");
	Lang("GR", "VIP_INVIS",					"Invisible ON/OFF");
	Lang("GR", "VIP_PICKUP",				"Pickup ON/OFF");
	Lang("GR", "VIP_NUKEBULL",				"NukeBullets");
	Lang("GR", "VIP_DOGOD",					"GodMode On");
	Lang("GR", "VIP_NOVA",					"GAS Nade");
	Lang("GR", "VIP_ROCKNUKE",				"Rocket Nuke");
	Lang("GR", "VIP_JETPACK",				"Jetpack");
	Lang("GR", "VIP_TELEGUN",				"Telegun");
	Lang("GR", "VIP_AMMO",					"Ammo");
	
	Lang("GR", "REAPER",					"t?p?? [{+actionslot 4}] ??a Reaper");
	Lang("GR", "REAPER_NOT_AVAILABLE",		"Reaper de? d?a??s?µ??");
	Lang("GR", "REAPER_INCOMING",				"Reaper e?se???µe???");
	Lang("GR", "FRIENDLY_REAPER",				"f?????? Reaper e?se???µe???");
	Lang("Gr", "ENEMY_REAPER",				"e????? Reaper e?se???µe???");
	Lang("GR", "YOUR_BOUNCED",				"^5Σε ^7έσπρωξε ο ^5Διαχειρηστής");
	Lang("GR", "BOUNCED_NOTIFY",			"$$CLANTAG$$[διαχειρηστής]: ^5Σπρώχτηκε ^7$$NAME$$.");
	Lang("GR", "APPEAR_AFK",				"^5Φένεται οτι έισαι ^7ΑΔΡΑΝΗΣ!");
	Lang("GR", "IS_AFK",					"$$NAME$$ ^5φένεται οτι είναι ^7ΑΔΡΑΝΗΣ!");
	Lang("GR", "MOVE_OR_KILL",				"^κουνήσου αλλίως θα ^7πεθάνεις!");
	Lang("GR", "ARTILLERY_NOT_AVAILABLE",	"Artillery μη διαθέσημο");
	Lang("GR", "PREDATOR_NOT_AVAILABLE",	"Predator μη διαθέσημο");
	Lang("GR", "STRAFE_NOT_AVAILABLE",		"Strafe Run μη διαθέσημο");	
	Lang("GR", "PREDATOR_STAND",			"Πρέπει να στέκεσαι οταν χρησημοποιείς το Predator");
	Lang("GR", "PREDATOR_INCOMING",			"Predator έρχεται");
	Lang("GR", "FRIENDLY_PREDATOR",			"Friendly Predator έρχεται");
	Lang("GR", "ENEMY_PREDATOR",			"Enemy Predator έρχεται");
	Lang("GR", "ARTILLERY_INCOMING",		"Artillery σε ετοιμότητα");
	Lang("GR", "FRIENDLY_ARTILLERY",		"Friendly Artillery σε ετοιμότητα");
	Lang("GR", "ENEMY_ARTILLERY",			"Enemy Artillery σε ετοιμότητα");
	Lang("GR", "STRAFE_INCOMING",			"Strafe Run έρχεται");
	Lang("GR", "FRIENDLY_STRAFE",			"Friendly Strafe Run έρχεται");
	Lang("GR", "ENEMY_STRAFE",				"Enemy Strafe Run έρχεται");
	Lang("GR", "PACKAGE_INCOMING",			"Care Package έρχεται");
	Lang("GR", "FRIENDLY_PACKAGE",			"Friendly Care Package έρχεται");
	Lang("GR", "ENEMY_PACKAGE",				"Enemy Care Package έρχεται");
	Lang("GR", "PACKAGE_POSITION",			"Δεν μπορείς να καλέσεις το πακέτο σε αυτό το σημείο");
	Lang("GR", "START_MAPVOTE",				"Πάτα FIRE για να ψηφίσεις");
	Lang("GR", "MAX_PRESTIGE",				"Έχεις ήδη φτάσει το ανώτατο κύρος!");
	Lang("GR", "NOT_REACHED_LVL",			"Δεν έχεις φτάσει το 55ο επίπεδο ακόμα");
	Lang("GR", "PRESTIGE_KILLS_LEFT",		"Απομένουν ακομα $$KILLS$$ θάνατοι!");
	Lang("GR", "WELCOME",					"Ευχαριστώ");
	Lang("GR", "FRAG_WAIT",					"Πρέπει να περιμένεις ακόμα $$TIME$$ δευτερόλεπτα");
	Lang("GR", "predator_mp",				"Πάτα [{+actionslot 4}] για	 PREDATOR");
	Lang("GR", "artillery_mp",				"Πάτα [{+actionslot 4}] για ARTILLERY");
	Lang("GR", "carepackage_mp",			"Πάτα [{+actionslot 4}] για CARE PACKAGE");
	Lang("GR", "strafe_mp",					"Πάτα [{+actionslot 4}] για Strafe Run");	
	Lang("GR", "PICKUP",					"Πάτα^3[[{+usereload}]] ^7για να πάρεις το ΠΑΚΕΤΟ");	
	Lang("GR", "NINJA",						"Πήρες την ιδιότητα Νίντζα!");	
	Lang("GR", "RUSHER",					"Πήρες την ιδιότητα Rusher!");	
	Lang("GR", "JUGGERNAUT",				"Πήρες την ιδιότητα Τουμπανιάρης!");	
	Lang("GR", "NUKE_BULLETS",				"Πήρες πυρηνικές σφαίρες!");	
	Lang("GR", "ACCURACY",				 	&"^5Ακρίβεια:^7 &&1");
	Lang("GR", "HELP_1",					"Αυτο το σέρβερ παρέχει νέα χαρακτηριστικά για να βελτιωθεί η \nεμπειρία παιχνιδιού, για αυτό υπάρχει το μενού\nεκέι μπορείς να αλλάξεις κύρος ή τα γραφικά.\nΜπορέις να το χρησημοποιήσεις πατώντας Ν δύο φορές\nή γράφοντας '!menu' στην συνομιλία."); // ΑΥΤΟ ΤΟ ΚΕΙΜΕΝΟ ΠΡΕΠΕΙ ΝΑ ΕΙΝΑΙ ΜΙΚΡΟΤΕΡΟ ΑΠΟ 256 ΧΑΡΑΚΤΗΡΕΣ
	Lang("GR", "HELP_2",					"Το σύμβολο-κέιμενο μπορεί να αλλάξει γράφοντας:\n!emblem <ΤΟ ΚΕΙΜΕΝΟ ΣΟΥ>");
	Lang("GR", "HELP_CLOSE",				"Πάτα ^3[[{+melee}]] ^7για να κλέισεις το μενού!");
	Lang("GR", "HELP_TIME_LEFT",			&"&&1δευτερόλεπτα μέχρι να μπορείς να το κλέισεις!");
	Lang("GR", "MENU_NAVI",					"^7Select: ^3[αριστερό ή δεξί κλικ]^7\nΧρήση: ^3[[{+activate}]]^7\nΈξοδος: ^3[[{+melee}]]");
	Lang("GR", "PRESTIGE_UNLOCK",			"Πρέπει να φτάσεις το  $$LEVEL$$ κύρος για να ξεκλιδώσεις το  $$FEATURE$$");
	Lang("GR", "NO_PERMISSION",				"Δεν μπορείς να το χρησημοποιήσεις!\nΑπέτυχε η δικαιοδοσία: $$PERMISSION$$");
	Lang("GR", "REFLECT_ON",				"Έπαθες ζημία ^5ενεργοποιήθηκε λόγω καμπερισμού!");
	Lang("GR", "SPAWN_PROTECTION",			&"Προστασία ζωής...^3&&1");
	Lang("GR", "nuke_mp",					"Πάτα [{+actionslot 4}] για ΠΥΡΗΝΙΚΗ");
	Lang("GR", "NUKE_NOT_AVAILABLE",		"ΠΥΡΗΝΙΚΗ μη διαθέσημη");	
	Lang("GR", "NUKE_INCOMING",				"ΠΥΡΗΝΙΚΗ έρχεται");
	Lang("GR", "FRIENDLY_NUKE",				"Φιλική ΠΥΡΗΝΙΚΗ έρχεται");
	Lang("GR", "ENEMY_NUKE",				"Αντίπαλη ΠΥΡΗΝΙΚΗ έρχεται");		
	Lang("GR", "TRAINING_AREA",				"Πάτα ^3[USE] ^7για να μπεις στη προπονητική ζώνη");
	Lang("GR", "GOT_KILLED",				&"Σε σκότωσε ο &&1.");	
	Lang("GR", "KILLED_PLAYER",				&"Σκότωσες τον &&1.");
	Lang("GR", "GOT_HONORED",				"Σου έδωσε δοξασία ο $$NAME$$");
	Lang("GR", "HONOR_PLAYER",				&"Πάτα ^3[FLASH] ^7για να δώσεις δοξασία ^7&&1 για αυτόν τον θάνατο.");
	Lang("GR", "CURRENT_HONOR",				&"Μάζεψες &&1 δοξασίες.");
	Lang("GR", "MENU_PRESTIGE",				"¶λλαξε κύρος");
	Lang("GR", "MENU_LASER",				"Εναλλαγή λείζερ (Κύρος 3)");
	Lang("EN", "MENU_THERMAL",				"Toggle Thermal (Prestige 2)");
	Lang("GR", "MENU_EMBLEM",				"¶λλαξε έμβλημα (Κύρος 1)");
	Lang("GR", "MENU_EMBLEM_DEFAULT",		"Αρχικό σχέδιο");
	Lang("GR", "MENU_EMBLEM_BLUE",			"Μπλέ σχέδιο");
	Lang("GR", "MENU_EMBLEM_RED",			"Κόκκινο σχέδιο");
	Lang("GR", "MENU_EMBLEM_GREEN",			"Πράσινο σχέδιο");
	Lang("GR", "MENU_EMBLEM_YELLOW",		"Yello Design");
	Lang("GR", "MENU_EMBLEM_ADMIN",			"RS-Member Design");
	Lang("GR", "MENU_EMBLEM_OWN",			"Δώσε το δικό σου σχέδιο");
	Lang("GR", "MENU_EMBLEM_3RS",			"^1RS^7' στυλ");
	Lang("GR", "MENU_FILM",					"Επέλεξε filmtweaks");
	Lang("GR", "MENU_TWEAK",				"Αυτά που μπορολυν να αλλάξουν");
	Lang("GR", "MENU_BRIGHT",				"Εναλλαγή Φωτηνότητα");
	Lang("GR", "MENU_FOG",					"Εναλλαγή ομλιχλη");
	Lang("GR", "MENU_LASER2",				"Εναλλαγή λειζερ");
	Lang("GR", "MENU_RULES",				"Εναλλαγή κανόνες παιχνιδιού");
	Lang("GR", "MENU_RESET",				"Διαγραφή όλων");
	Lang("GR", "MENU_TWEAKS",				"Εναλλαγή Filmtweaks");
	Lang("GR", "MENU_DEV",					"Τομέας διαχειρηστή");
	Lang("GR", "MENU_VIP",					"Vip section");
	Lang("GR", "RESPAWN_IN",				&"Αναγέννηση σε : &&1");
	Lang("GR", "TRANSLATED_BY",				"Greek translation by WalkingNoodle");
	//-------------------------DANISH--------------------------
	Lang("DK", "VIP_DM",					"DeathMachine ON/OFF");
	Lang("DK", "VIP_FREEZE",				"FreezeAll ON/OFF");
	Lang("DK", "VIP_INVIS",					"Invisible ON/OFF");
	Lang("DK", "VIP_PICKUP",				"Pickup ON/OFF");
	Lang("DK", "VIP_NUKEBULL",				"NukeBullets");
	Lang("DK", "VIP_DOGOD",					"GodMode On");
	Lang("DK", "VIP_NOVA",					"GAS Nade");
	Lang("DK", "VIP_ROCKNUKE",				"Rocket Nuke");
	Lang("DK", "VIP_JETPACK",				"Jetpack");
	Lang("DK", "VIP_TELEGUN",				"Telegun");
	Lang("DK", "VIP_AMMO",					"Ammo");
	
	Lang("DK", "REAPER",					"t?p?? [{+actionslot 4}] ??a Reaper");
	Lang("DK", "REAPER_NOT_AVAILABLE",		"Reaper de? d?a??s?µ??");
	Lang("DK", "REAPER_INCOMING",				"Reaper e?se???µe???");
	Lang("DK", "FRIENDLY_REAPER",				"f?????? Reaper e?se???µe???");
	Lang("DK", "ENEMY_REAPER",				"e????? Reaper e?se???µe???");
	Lang("DK", "YOUR_BOUNCED",				"^5Du var ^7returneret ^5af Adminen");
	Lang("DK", "BOUNCED_NOTIFY",			"$$CLANTAG$$[admin]: ^5Returneret ^7$$NAME$$.");
	Lang("DK", "APPEAR_AFK",				"^5Du ser ud til at vζre ^7AFK!");
	Lang("DK", "IS_AFK",					"$$NAME$$ ^5ser ud til at vζre ^7AFK!");
	Lang("DK", "MOVE_OR_KILL",				"^5Flyt dig eller du vil blive ^7drζbt!");
	Lang("DK", "ARTILLERY_NOT_AVAILABLE",	"Artilleri ikke tilgζngelig");
	Lang("DK", "PREDATOR_NOT_AVAILABLE",	"Predator ikke tilgζngelig");
	Lang("DK", "STRAFE_NOT_AVAILABLE",		"Helikopter ikke tilgζngelig");	
	Lang("DK", "PREDATOR_STAND",			"Du skal stε oprejst, for at bruge Predator");
	Lang("DK", "PREDATOR_INCOMING",			"Predator pε vej");
	Lang("DK", "FRIENDLY_PREDATOR",			"Venlig Predator pε vej");
	Lang("DK", "ENEMY_PREDATOR",			"Fjendtlig Predator pε vej");
	Lang("DK", "ARTILLERY_INCOMING",		"Artilleri pε stand by");
	Lang("DK", "FRIENDLY_ARTILLERY",		"Venligt Artilleri pε stand by");
	Lang("DK", "ENEMY_ARTILLERY",			"Fjendtligt Artilleri pε stand by");
	Lang("DK", "STRAFE_INCOMING",			"Helikopter pε vej");
	Lang("DK", "FRIENDLY_STRAFE",			"Venlig Helikopter pε vej");
	Lang("DK", "ENEMY_STRAFE",				"Fjendtlig Helikopter pε vej");
	Lang("DK", "PACKAGE_INCOMING",			"Forplejningspakke pε vej");
	Lang("DK", "FRIENDLY_PACKAGE",			"Venlig Forplejningspakke pε vej");
	Lang("DK", "ENEMY_PACKAGE",				"Fjendtlig Forplejningspakke pε vej");
	Lang("DK", "PACKAGE_POSITION",			"Du kan ikke kalde pε DK Forplejningspakke pε nuvζrende position");
	Lang("DK", "START_MAPVOTE",				"Tryk Skyd for at stemme");
	Lang("DK", "MAX_PRESTIGE",				"Du har allerede nεet det maksimale prestigeniveau!");
	Lang("DK", "NOT_REACHED_LVL",			"Du har ikke opnεet level 55 endnu");
	Lang("DK", "PRESTIGE_KILLS_LEFT",		"Der er stadig $$KILLS$$ drab tilbage!");
	Lang("DK", "WELCOME",					"Velkommen");
	Lang("DK", "FRAG_WAIT",					"Du skal vente $$TIME$$ sekunder");
	Lang("DK", "predator_mp",				"Tryk [{+actionslot 4}] for at aktivere PREDATOR");
	Lang("DK", "artillery_mp",				"Tryk [{+actionslot 4}] for at aktivere ARTILLERI");
	Lang("DK", "carepackage_mp",			"Tryk [{+actionslot 4}] for at aktivere FORPLEJNINGSPAKKE");
	Lang("DK", "strafe_mp",					"Tryk [{+actionslot 4}] for at aktivere HELIKOPTER");	
	Lang("DK", "PICKUP",					"Tryk ^3[[{+usereload}]] ^7for at opsamle Forplejningspakke");	
	Lang("DK", "NINJA",						"Du fik evnen som Ninja!");	
	Lang("DK", "RUSHER",					"Du fik evnen som Stormer!");	
	Lang("DK", "JUGGERNAUT",				"Du fik evnen som Juggernaut!");	
	Lang("DK", "NUKE_BULLETS",				"Du fik Atombombeskud!");	
	Lang("DK", "ACCURACY",				 	&"^5Prζcision:^7 &&1");
	Lang("DK", "HELP_1",					"Denne server tilbyder nye features for at forbedre din\noplevelse, derfor er der DK Menu, hvor du\nkan modtage prestige og ζndre grafiske indstillinger.\nDet kan εbnes ved at trykke pε Nightvision-knappen 2 gange\neller ved at skrive '!menu' i chatten."); // THIS TEXT MUST BE SHORTER THEN 256 chars
	Lang("DK", "HELP_2",					"Emblemteksten kan ζndres ved at skrive:\n!emblem <DIN TEKST>");
	Lang("DK", "HELP_CLOSE",				"Tryk ^3[[{+melee}]] ^7for at lukke denne Menu!");
	Lang("DK", "HELP_TIME_LEFT",			&"&&1 sekunder tilbage indtil du kan lukke!");
	Lang("DK", "MENU_NAVI",					"^7Vζlg: ^3[Hψjre eller venstre museknap]^7\nBrug: ^3[[{+activate}]]^7\nForlad: ^3[[{+melee}]]");
	Lang("DK", "PRESTIGE_UNLOCK",			"Du bliver nψdt til at opnε Prestige Level $$LEVEL$$ for at εbne $$FEATURE$$");
	Lang("DK", "NO_PERMISSION",				"Du har ingen ret til at bruge dette!\nFejlslεet tilladelse: $$PERMISSION$$");
	Lang("DK", "REFLECT_ON",				"Skades reflektion ^5aktiveret pε grund af camp!");
	Lang("DK", "SPAWN_PROTECTION",			&"Spawnbeskyttelse...^3&&1");
	Lang("DK", "nuke_mp",					"Tryk [{+actionslot 4}] for at aktivere ATOMBOMBE");
	Lang("DK", "NUKE_NOT_AVAILABLE",		"Atombombe ikke tilgζngelig");	
	Lang("DK", "NUKE_INCOMING",				"Atombombe pε vej");
	Lang("DK", "FRIENDLY_NUKE",				"Venlig Atombombe pε vej");
	Lang("DK", "ENEMY_NUKE",				"Fjendtlig Atombombe pε vej");		
	Lang("DK", "TRAINING_AREA",				"Tryk ^3[BRUG] ^7for at komme ind pε trζningsarealet");
	Lang("DK", "GOT_KILLED",				&"Drζbt af &&1.");	
	Lang("DK", "KILLED_PLAYER",				&"Du drζbte &&1.");
	Lang("DK", "GOT_HONORED",				"Du har fεet ζre af $$NAME$$");
	Lang("DK", "HONOR_PLAYER",				&"Tryk ^3[FLASH] ^7for at ζre ^7&&1 for dette drab.");
	Lang("DK", "CURRENT_HONOR",				&"Samlet &&1 ζre.");	
	Lang("DK", "MENU_PRESTIGE",				"Gε ind i Prestige");
	Lang("DK", "MENU_PRESTIGE",				"Gε ind i Prestige");
	Lang("DK", "MENU_LASER",				"Skift Laser (Prestige 3)");
	Lang("EN", "MENU_THERMAL",				"Toggle Thermal (Prestige 2)");
	Lang("DK", "MENU_EMBLEM",				"Skift Emblem (Prestige 1)");
	Lang("DK", "MENU_EMBLEM_DEFAULT",		"Valgfrit Design");
	Lang("DK", "MENU_EMBLEM_BLUE",			"Blεt Design");
	Lang("DK", "MENU_EMBLEM_RED",			"Rψdt Design");
	Lang("DK", "MENU_EMBLEM_GREEN",			"Grψnt Design");
	Lang("DK", "MENU_EMBLEM_YELLOW",		"Yello Design");
	Lang("DK", "MENU_EMBLEM_ADMIN",			"RS-Member Design");
	Lang("DK", "MENU_EMBLEM_OWN",			"Indtast eget tema");
	Lang("DK", "MENU_EMBLEM_3RS",			"^1RS^7' Stil");
	Lang("DK", "MENU_FILM",					"Vζlg Filmklip");
	Lang("DK", "MENU_TWEAK",				"Justeringer");
	Lang("DK", "MENU_BRIGHT",				"Justιr Lysstyrke");
	Lang("DK", "MENU_FOG",					"Justιr Tεge");
	Lang("DK", "MENU_LASER2",				"Justιr Laser");
	Lang("DK", "MENU_RULES",				"Skift Spilleregler");
	Lang("DK", "MENU_RESET",				"Reset alt");
	Lang("DK", "MENU_TWEAKS",				"Justιr Filmklip");
	Lang("DK", "MENU_DEV",					"Admin afdeling");
	Lang("DK", "MENU_VIP",					"Vip section");
	Lang("DK", "TRANSLATED_BY",				"Danish translation by Truster");
	//------------------------------Croatian---------------------------------
	Lang("HR", "VIP_DM",					"DeathMachine ON/OFF");
	Lang("HR", "VIP_FREEZE",				"FreezeAll ON/OFF");
	Lang("HR", "VIP_INVIS",					"Invisible ON/OFF");
	Lang("HR", "VIP_PICKUP",				"Pickup ON/OFF");
	Lang("HR", "VIP_NUKEBULL",				"NukeBullets");
	Lang("HR", "VIP_DOGOD",					"GodMode On");
	Lang("HR", "VIP_NOVA",					"GAS Nade");
	Lang("HR", "VIP_ROCKNUKE",				"Rocket Nuke");
	Lang("HR", "VIP_JETPACK",				"Jetpack");
	Lang("HR", "VIP_TELEGUN",				"Telegun");
	Lang("HR", "VIP_AMMO",					"Ammo");
	
	Lang("HR", "REAPER",					"tisk [{+actionslot 4}] pro Reaper");
	Lang("HR", "REAPER_NOT_AVAILABLE",		"Reaper ne dostupnύ");
	Lang("HR", "REAPER_INCOMING",				"Reaper prichαzejνcν");
	Lang("HR", "FRIENDLY_REAPER",				"prαtelskύ Reaper prichαzejνcν");
	Lang("HR", "ENEMY_REAPER",				"neprνtel Reaper prichαzejνcν");
	Lang("HR", "YOUR_BOUNCED",				"^5Odbouncean ^7si ^5od strane admina");
	Lang("HR", "BOUNCED_NOTIFY",			"$$CLANTAG$$[admin]: ^5Odbouncean ^7$$NAME$$.");
	Lang("HR", "APPEAR_AFK",				"^5Izgleda da si ^7AFK!");
	Lang("HR", "IS_AFK",					"$$NAME$$ ^5je ^7AFK!");
	Lang("HR", "MOVE_OR_KILL",				"^5Pomakni se ili ces biti ^7ubijen!");
	Lang("HR", "ARTILLERY_NOT_AVAILABLE",	"Artiljerija nije dostupna");
	Lang("HR", "PREDATOR_NOT_AVAILABLE",	"Predator nije dostupan");
	Lang("HR", "STRAFE_NOT_AVAILABLE",		"Helikopter not available");	
	Lang("HR", "PREDATOR_STAND",			"Moras stajati da bi koristio Predator");
	Lang("HR", "PREDATOR_INCOMING",			"Predator dolazi");
	Lang("HR", "FRIENDLY_PREDATOR",			"Prijateljski Predator dolazi");
	Lang("HR", "ENEMY_PREDATOR",			"Neprijateljski Predator dolazi");
	Lang("HR", "ARTILLERY_INCOMING",		"Artiljerija u pripravnosti");
	Lang("HR", "FRIENDLY_ARTILLERY",		"Prijateljska artiljerija u pripravnosti");
	Lang("HR", "ENEMY_ARTILLERY",			"Neprijateljska artiljerija u pripravnosti");
	Lang("HR", "STRAFE_INCOMING",			"Helikopter dolazi!");
	Lang("HR", "FRIENDLY_STRAFE",			"Prijateljski helikopter dolazi!");
	Lang("HR", "ENEMY_STRAFE",				"Neprijateljski helikopter dolazi!");
	Lang("HR", "PACKAGE_INCOMING",			"Paket za njegu dolazi");
	Lang("HR", "FRIENDLY_PACKAGE",			"Prijateljski paket za njegu");
	Lang("HR", "ENEMY_PACKAGE",				"Neprijateljski paket za njegu");
	Lang("HR", "PACKAGE_POSITION",			"Paket za njegu ne moze biti pozvan na ovoj poziciji");
	Lang("HR", "START_MAPVOTE",				"^1>> ^7Pritisni Napad za glasanje!");
	Lang("HR", "MAX_PRESTIGE",				"Vec si dostigao maksimalni Prestige!");
	Lang("HR", "NOT_REACHED_LVL",			"Nisi dostigao lvl 55");
	Lang("HR", "PRESTIGE_KILLS_LEFT",		"Ostalo ti je jos $$KILLS$$ killova");
	Lang("HR", "WELCOME",					"Dobrodosao");
	Lang("HR", "FRAG_WAIT",					"Moras pricekati $$TIME$$ sekundi");
	Lang("HR", "predator_mp",				"Pritisni [{+actionslot 4}] za PREDATOR");
	Lang("HR", "artillery_mp",				"Pritisni [{+actionslot 4}] za ARTILLERY");
	Lang("HR", "carepackage_mp",			"Pritisni [{+actionslot 4}] za CARE PACKAGE");
	Lang("HR", "strafe_mp",					"Pritisni [{+actionslot 4}] za Strafe Run");	
	Lang("HR", "PICKUP",					"Pritisni ^3[[{+usereload}]] ^7da pokupis Paket za njegu");	
	Lang("HR", "NINJA",						"Dobio si mogucnost: Ninja!");	
	Lang("HR", "RUSHER",					"Dobio si mogucnost: Rusher!");	
	Lang("HR", "JUGGERNAUT",				"Dobio si mogucnost: Juggernaut!");	
	Lang("HR", "NUKE_BULLETS",				"Dobio si: Nuklearne metke!");	
	Lang("HR", "ACCURACY",				 	&"^5Preciznost:^7 &&1");
	Lang("HR", "HELP_1",					"Ovaj Server nudi mnoge nove znacajke kako bi poboljsali svoje\ngaming iskustvo, stoga postoji izbornik gdje\nmozes izabrati prestige i promjeniti svoje graficke postavke.\nMoze biti otvoren ako kliknes Nocnu viziju 2x\nili napisati '!menu' u chat."); // THIS TEXT MUST BE SHORTER THEN 256 chars
	Lang("HR", "HELP_2",					"Text na katrici moze biti promijenjen kada upises:\n!emblem <Tekst>");
	Lang("HR", "HELP_CLOSE",				"Pritisni ^3[[{+melee}]] ^7da bi zatvorio meni!");
	Lang("HR", "HELP_TIME_LEFT",			&"&&1 sekunda preostalo dok ne mozes zatvoriti!");
	Lang("HR", "MENU_NAVI",					"^7Postavke: ^3[Desni ili Lijevi Mis]^7\nKoristi: ^3[[{+activate}]]^7\nIzadji: ^3[[{+melee}]]");
	Lang("HR", "PRESTIGE_UNLOCK",			"Dostigni prestige lvl $$LEVEL$$ da otkljucas $$FEATURE$$");
	Lang("HR", "NO_PERMISSION",				"Nemas dozvolu da koristis ovo!\nNije odobrena dozvola: $$PERMISSION$$");
	Lang("HR", "REFLECT_ON",				"Health ti je smanjen ^ 5zbog kampa!");
	Lang("HR", "SPAWN_PROTECTION",			&"Spawn zastita...^3&&1");
	Lang("HR", "nuke_mp",					"Pritisni [{+actionslot 4}] za Nuklearnu bombu");
	Lang("HR", "NUKE_NOT_AVAILABLE",		"Nuklearna bomba nije dostupna!");	
	Lang("HR", "NUKE_INCOMING",				"Nuklearna bomba dolazi!");
	Lang("HR", "FRIENDLY_NUKE",				"Prijateljska nuklearna bomba dolazi!");
	Lang("HR", "ENEMY_NUKE",				"Neprijateljska nuklearna bomba dolazi");		
	Lang("HR", "TRAINING_AREA",				"Pritisni ^3[USE] ^7da udes u trening arenu");
	Lang("HR", "GOT_KILLED",				&"Ubio te &&1.");	
	Lang("HR", "KILLED_PLAYER",				&"Ubio si &&1.");
	Lang("HR", "GOT_HONORED",				"Dobio si cast od: $$NAME$$");
	Lang("HR", "HONOR_PLAYER",				&"Pritisni ^3[FLASH] ^7da das cast ^7&&1 za ovaj kill.");
	Lang("HR", "CURRENT_HONOR",				&"Skupio &&1 casti.");
	Lang("HR", "MENU_PRESTIGE",				"Ukucaj Prestige"); 			
	Lang("HR", "MENU_LASER",				"Prebaci Laser (Prestige 3)");
	Lang("EN", "MENU_THERMAL",				"Toggle Thermal (Prestige 2)");
	Lang("HR", "MENU_EMBLEM",				"Promjeni Emblem (Prestige 1)");
	Lang("HR", "MENU_EMBLEM_DEFAULT",		"Normalni Dizajn");				
	Lang("HR", "MENU_EMBLEM_BLUE",			"Plavi Dizajn");				
	Lang("HR", "MENU_EMBLEM_RED",			"Crveni Dizajn");				
	Lang("HR", "MENU_EMBLEM_GREEN",			"Zeleni Dizajn");
	Lang("HR", "MENU_EMBLEM_YELLOW",		"Yello Design");
	Lang("HR", "MENU_EMBLEM_ADMIN",			"RS-Member Design");
	Lang("HR", "MENU_EMBLEM_OWN",			"Ukucaj svoju temu");			
	Lang("HR", "MENU_EMBLEM_3RS",			"^1RS^7' Dizajn");				
	Lang("HR", "MENU_FILM",					"Odaberi Filmtweak");			
	Lang("HR", "MENU_TWEAK",				"Tweakables");					
	Lang("HR", "MENU_BRIGHT",				"Prebacivanje Fullbright-a");	
	Lang("HR", "MENU_FOG",					"Prebacivanje Fog-a");			
	Lang("HR", "MENU_LASER2",				"Prebacivanje lasera");			
	Lang("HR", "MENU_RULES",				"Promjeni Pravila");			
	Lang("HR", "MENU_RESET",				"Resetiraj sve");				
	Lang("HR", "MENU_TWEAKS",				"Prebacivanje Filmtweakova");	
	Lang("HR", "MENU_DEV",					"Sekcija Admina");
	Lang("HR", "MENU_VIP",					"Vip section");
	Lang("HR", "MENU_EDITOR",				"Kreiraj klasu");				
	Lang("HR", "RESPAWN_IN",				&"Spawnat ces se za: &&1");
	Lang("HR", "EARNED_XP",					&"^5Prikupljeno XP-a: ^7&&1");
	Lang("HR", "TRANSLATED_BY",				"Hrvatski.Preveo:TonzZzy <3,xf:duviii24"); //you can credit yourself here but also write it in your language

	LanguageDefinition("CH","DE"); 
	LanguageDefinition("AT","DE"); 
	LanguageDefinition("SE","NO"); 
	LanguageDefinition("BA","HR"); 
}